# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proio/proto/proio.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proio/proto/proio.proto',
  package='proio.proto',
  syntax='proto3',
  serialized_pb=_b('\n\x17proio/proto/proio.proto\x12\x0bproio.proto\"(\n\nNamedBytes\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\xb3\x02\n\x0c\x42ucketHeader\x12\x0f\n\x07nEvents\x18\x01 \x01(\x04\x12\x12\n\nbucketSize\x18\x02 \x01(\x04\x12\x37\n\x0b\x63ompression\x18\x03 \x01(\x0e\x32\".proio.proto.BucketHeader.CompType\x12\x32\n\x04type\x18\x04 \x01(\x0e\x32$.proio.proto.BucketHeader.BucketType\x12\x17\n\x0f\x66ileDescriptors\x18\x05 \x03(\x0c\x12)\n\x08metaData\x18\x06 \x03(\x0b\x32\x17.proio.proto.NamedBytes\"\'\n\x08\x43ompType\x12\x08\n\x04NONE\x10\x00\x12\x08\n\x04GZIP\x10\x01\x12\x07\n\x03LZ4\x10\x02\"$\n\nBucketType\x12\n\n\x06\x45VENTS\x10\x00\x12\n\n\x06\x46OOTER\x10\x01\"\x16\n\x03Tag\x12\x0f\n\x07\x65ntries\x18\x01 \x03(\x04\"$\n\x03\x41ny\x12\x0c\n\x04type\x18\x01 \x01(\x04\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"\xf7\x02\n\x05\x45vent\x12*\n\x04tags\x18\x01 \x03(\x0b\x32\x1c.proio.proto.Event.TagsEntry\x12\x10\n\x08nEntries\x18\x02 \x01(\x04\x12\x30\n\x07\x65ntries\x18\x03 \x03(\x0b\x32\x1f.proio.proto.Event.EntriesEntry\x12\x0e\n\x06nTypes\x18\x04 \x01(\x04\x12,\n\x05types\x18\x05 \x03(\x0b\x32\x1d.proio.proto.Event.TypesEntry\x12\x11\n\ttimestamp\x18\x06 \x01(\x04\x1a=\n\tTagsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.proio.proto.Tag:\x02\x38\x01\x1a@\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x04\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.proio.proto.Any:\x02\x38\x01\x1a,\n\nTypesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x04\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42=\n\x05proioB\x05ProtoZ-github.com/decibelcooper/proio/go-proio/protob\x06proto3')
)



_BUCKETHEADER_COMPTYPE = _descriptor.EnumDescriptor(
  name='CompType',
  full_name='proio.proto.BucketHeader.CompType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GZIP', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LZ4', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=313,
  serialized_end=352,
)
_sym_db.RegisterEnumDescriptor(_BUCKETHEADER_COMPTYPE)

_BUCKETHEADER_BUCKETTYPE = _descriptor.EnumDescriptor(
  name='BucketType',
  full_name='proio.proto.BucketHeader.BucketType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EVENTS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FOOTER', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=354,
  serialized_end=390,
)
_sym_db.RegisterEnumDescriptor(_BUCKETHEADER_BUCKETTYPE)


_NAMEDBYTES = _descriptor.Descriptor(
  name='NamedBytes',
  full_name='proio.proto.NamedBytes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='proio.proto.NamedBytes.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='proio.proto.NamedBytes.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=80,
)


_BUCKETHEADER = _descriptor.Descriptor(
  name='BucketHeader',
  full_name='proio.proto.BucketHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nEvents', full_name='proio.proto.BucketHeader.nEvents', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bucketSize', full_name='proio.proto.BucketHeader.bucketSize', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='compression', full_name='proio.proto.BucketHeader.compression', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='proio.proto.BucketHeader.type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fileDescriptors', full_name='proio.proto.BucketHeader.fileDescriptors', index=4,
      number=5, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metaData', full_name='proio.proto.BucketHeader.metaData', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BUCKETHEADER_COMPTYPE,
    _BUCKETHEADER_BUCKETTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=390,
)


_TAG = _descriptor.Descriptor(
  name='Tag',
  full_name='proio.proto.Tag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entries', full_name='proio.proto.Tag.entries', index=0,
      number=1, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=392,
  serialized_end=414,
)


_ANY = _descriptor.Descriptor(
  name='Any',
  full_name='proio.proto.Any',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='proio.proto.Any.type', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='proio.proto.Any.payload', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=416,
  serialized_end=452,
)


_EVENT_TAGSENTRY = _descriptor.Descriptor(
  name='TagsEntry',
  full_name='proio.proto.Event.TagsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='proio.proto.Event.TagsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='proio.proto.Event.TagsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=657,
  serialized_end=718,
)

_EVENT_ENTRIESENTRY = _descriptor.Descriptor(
  name='EntriesEntry',
  full_name='proio.proto.Event.EntriesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='proio.proto.Event.EntriesEntry.key', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='proio.proto.Event.EntriesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=720,
  serialized_end=784,
)

_EVENT_TYPESENTRY = _descriptor.Descriptor(
  name='TypesEntry',
  full_name='proio.proto.Event.TypesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='proio.proto.Event.TypesEntry.key', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='proio.proto.Event.TypesEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=786,
  serialized_end=830,
)

_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='proio.proto.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tags', full_name='proio.proto.Event.tags', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nEntries', full_name='proio.proto.Event.nEntries', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entries', full_name='proio.proto.Event.entries', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nTypes', full_name='proio.proto.Event.nTypes', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='types', full_name='proio.proto.Event.types', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='proio.proto.Event.timestamp', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_EVENT_TAGSENTRY, _EVENT_ENTRIESENTRY, _EVENT_TYPESENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=455,
  serialized_end=830,
)

_BUCKETHEADER.fields_by_name['compression'].enum_type = _BUCKETHEADER_COMPTYPE
_BUCKETHEADER.fields_by_name['type'].enum_type = _BUCKETHEADER_BUCKETTYPE
_BUCKETHEADER.fields_by_name['metaData'].message_type = _NAMEDBYTES
_BUCKETHEADER_COMPTYPE.containing_type = _BUCKETHEADER
_BUCKETHEADER_BUCKETTYPE.containing_type = _BUCKETHEADER
_EVENT_TAGSENTRY.fields_by_name['value'].message_type = _TAG
_EVENT_TAGSENTRY.containing_type = _EVENT
_EVENT_ENTRIESENTRY.fields_by_name['value'].message_type = _ANY
_EVENT_ENTRIESENTRY.containing_type = _EVENT
_EVENT_TYPESENTRY.containing_type = _EVENT
_EVENT.fields_by_name['tags'].message_type = _EVENT_TAGSENTRY
_EVENT.fields_by_name['entries'].message_type = _EVENT_ENTRIESENTRY
_EVENT.fields_by_name['types'].message_type = _EVENT_TYPESENTRY
DESCRIPTOR.message_types_by_name['NamedBytes'] = _NAMEDBYTES
DESCRIPTOR.message_types_by_name['BucketHeader'] = _BUCKETHEADER
DESCRIPTOR.message_types_by_name['Tag'] = _TAG
DESCRIPTOR.message_types_by_name['Any'] = _ANY
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NamedBytes = _reflection.GeneratedProtocolMessageType('NamedBytes', (_message.Message,), dict(
  DESCRIPTOR = _NAMEDBYTES,
  __module__ = 'proio.proto.proio_pb2'
  # @@protoc_insertion_point(class_scope:proio.proto.NamedBytes)
  ))
_sym_db.RegisterMessage(NamedBytes)

BucketHeader = _reflection.GeneratedProtocolMessageType('BucketHeader', (_message.Message,), dict(
  DESCRIPTOR = _BUCKETHEADER,
  __module__ = 'proio.proto.proio_pb2'
  # @@protoc_insertion_point(class_scope:proio.proto.BucketHeader)
  ))
_sym_db.RegisterMessage(BucketHeader)

Tag = _reflection.GeneratedProtocolMessageType('Tag', (_message.Message,), dict(
  DESCRIPTOR = _TAG,
  __module__ = 'proio.proto.proio_pb2'
  # @@protoc_insertion_point(class_scope:proio.proto.Tag)
  ))
_sym_db.RegisterMessage(Tag)

Any = _reflection.GeneratedProtocolMessageType('Any', (_message.Message,), dict(
  DESCRIPTOR = _ANY,
  __module__ = 'proio.proto.proio_pb2'
  # @@protoc_insertion_point(class_scope:proio.proto.Any)
  ))
_sym_db.RegisterMessage(Any)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), dict(

  TagsEntry = _reflection.GeneratedProtocolMessageType('TagsEntry', (_message.Message,), dict(
    DESCRIPTOR = _EVENT_TAGSENTRY,
    __module__ = 'proio.proto.proio_pb2'
    # @@protoc_insertion_point(class_scope:proio.proto.Event.TagsEntry)
    ))
  ,

  EntriesEntry = _reflection.GeneratedProtocolMessageType('EntriesEntry', (_message.Message,), dict(
    DESCRIPTOR = _EVENT_ENTRIESENTRY,
    __module__ = 'proio.proto.proio_pb2'
    # @@protoc_insertion_point(class_scope:proio.proto.Event.EntriesEntry)
    ))
  ,

  TypesEntry = _reflection.GeneratedProtocolMessageType('TypesEntry', (_message.Message,), dict(
    DESCRIPTOR = _EVENT_TYPESENTRY,
    __module__ = 'proio.proto.proio_pb2'
    # @@protoc_insertion_point(class_scope:proio.proto.Event.TypesEntry)
    ))
  ,
  DESCRIPTOR = _EVENT,
  __module__ = 'proio.proto.proio_pb2'
  # @@protoc_insertion_point(class_scope:proio.proto.Event)
  ))
_sym_db.RegisterMessage(Event)
_sym_db.RegisterMessage(Event.TagsEntry)
_sym_db.RegisterMessage(Event.EntriesEntry)
_sym_db.RegisterMessage(Event.TypesEntry)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\005proioB\005ProtoZ-github.com/decibelcooper/proio/go-proio/proto'))
_EVENT_TAGSENTRY.has_options = True
_EVENT_TAGSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_EVENT_ENTRIESENTRY.has_options = True
_EVENT_ENTRIESENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_EVENT_TYPESENTRY.has_options = True
_EVENT_TYPESENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
