// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proio/model/eic.proto

/*
	Package eic is a generated protocol buffer package.

	It is generated from these files:
		proio/model/eic.proto

	It has these top-level messages:
		XYZTInt
		XYZTDouble
		XYZTFloat
		XYZInt
		XYZDouble
		XYZFloat
		Particle
		SimHit
*/
package eic

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type XYZTInt struct {
	X int64 `protobuf:"zigzag64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int64 `protobuf:"zigzag64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z int64 `protobuf:"zigzag64,3,opt,name=z,proto3" json:"z,omitempty"`
	T int64 `protobuf:"zigzag64,4,opt,name=t,proto3" json:"t,omitempty"`
}

func (m *XYZTInt) Reset()                    { *m = XYZTInt{} }
func (m *XYZTInt) String() string            { return proto.CompactTextString(m) }
func (*XYZTInt) ProtoMessage()               {}
func (*XYZTInt) Descriptor() ([]byte, []int) { return fileDescriptorEic, []int{0} }

func (m *XYZTInt) GetX() int64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *XYZTInt) GetY() int64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *XYZTInt) GetZ() int64 {
	if m != nil {
		return m.Z
	}
	return 0
}

func (m *XYZTInt) GetT() int64 {
	if m != nil {
		return m.T
	}
	return 0
}

type XYZTDouble struct {
	X float64 `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float64 `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
	T float64 `protobuf:"fixed64,4,opt,name=t,proto3" json:"t,omitempty"`
}

func (m *XYZTDouble) Reset()                    { *m = XYZTDouble{} }
func (m *XYZTDouble) String() string            { return proto.CompactTextString(m) }
func (*XYZTDouble) ProtoMessage()               {}
func (*XYZTDouble) Descriptor() ([]byte, []int) { return fileDescriptorEic, []int{1} }

func (m *XYZTDouble) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *XYZTDouble) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *XYZTDouble) GetZ() float64 {
	if m != nil {
		return m.Z
	}
	return 0
}

func (m *XYZTDouble) GetT() float64 {
	if m != nil {
		return m.T
	}
	return 0
}

type XYZTFloat struct {
	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float32 `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	T float32 `protobuf:"fixed32,4,opt,name=t,proto3" json:"t,omitempty"`
}

func (m *XYZTFloat) Reset()                    { *m = XYZTFloat{} }
func (m *XYZTFloat) String() string            { return proto.CompactTextString(m) }
func (*XYZTFloat) ProtoMessage()               {}
func (*XYZTFloat) Descriptor() ([]byte, []int) { return fileDescriptorEic, []int{2} }

func (m *XYZTFloat) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *XYZTFloat) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *XYZTFloat) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

func (m *XYZTFloat) GetT() float32 {
	if m != nil {
		return m.T
	}
	return 0
}

type XYZInt struct {
	X int64 `protobuf:"zigzag64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int64 `protobuf:"zigzag64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z int64 `protobuf:"zigzag64,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (m *XYZInt) Reset()                    { *m = XYZInt{} }
func (m *XYZInt) String() string            { return proto.CompactTextString(m) }
func (*XYZInt) ProtoMessage()               {}
func (*XYZInt) Descriptor() ([]byte, []int) { return fileDescriptorEic, []int{3} }

func (m *XYZInt) GetX() int64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *XYZInt) GetY() int64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *XYZInt) GetZ() int64 {
	if m != nil {
		return m.Z
	}
	return 0
}

type XYZDouble struct {
	X float64 `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float64 `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (m *XYZDouble) Reset()                    { *m = XYZDouble{} }
func (m *XYZDouble) String() string            { return proto.CompactTextString(m) }
func (*XYZDouble) ProtoMessage()               {}
func (*XYZDouble) Descriptor() ([]byte, []int) { return fileDescriptorEic, []int{4} }

func (m *XYZDouble) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *XYZDouble) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *XYZDouble) GetZ() float64 {
	if m != nil {
		return m.Z
	}
	return 0
}

type XYZFloat struct {
	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float32 `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (m *XYZFloat) Reset()                    { *m = XYZFloat{} }
func (m *XYZFloat) String() string            { return proto.CompactTextString(m) }
func (*XYZFloat) ProtoMessage()               {}
func (*XYZFloat) Descriptor() ([]byte, []int) { return fileDescriptorEic, []int{5} }

func (m *XYZFloat) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *XYZFloat) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *XYZFloat) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

type Particle struct {
	Parent []uint64 `protobuf:"varint,1,rep,packed,name=parent" json:"parent,omitempty"`
	Child  []uint64 `protobuf:"varint,2,rep,packed,name=child" json:"child,omitempty"`
	Pdg    int32    `protobuf:"zigzag32,3,opt,name=pdg,proto3" json:"pdg,omitempty"`
	// position in mm and time in ns
	Vertex *XYZTDouble `protobuf:"bytes,4,opt,name=vertex" json:"vertex,omitempty"`
	// momentum in GeV
	P *XYZDouble `protobuf:"bytes,5,opt,name=p" json:"p,omitempty"`
	// mass in GeV
	Mass   float64   `protobuf:"fixed64,6,opt,name=mass,proto3" json:"mass,omitempty"`
	Charge float32   `protobuf:"fixed32,7,opt,name=charge,proto3" json:"charge,omitempty"`
	Spin   *XYZFloat `protobuf:"bytes,8,opt,name=spin" json:"spin,omitempty"`
}

func (m *Particle) Reset()                    { *m = Particle{} }
func (m *Particle) String() string            { return proto.CompactTextString(m) }
func (*Particle) ProtoMessage()               {}
func (*Particle) Descriptor() ([]byte, []int) { return fileDescriptorEic, []int{6} }

func (m *Particle) GetParent() []uint64 {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *Particle) GetChild() []uint64 {
	if m != nil {
		return m.Child
	}
	return nil
}

func (m *Particle) GetPdg() int32 {
	if m != nil {
		return m.Pdg
	}
	return 0
}

func (m *Particle) GetVertex() *XYZTDouble {
	if m != nil {
		return m.Vertex
	}
	return nil
}

func (m *Particle) GetP() *XYZDouble {
	if m != nil {
		return m.P
	}
	return nil
}

func (m *Particle) GetMass() float64 {
	if m != nil {
		return m.Mass
	}
	return 0
}

func (m *Particle) GetCharge() float32 {
	if m != nil {
		return m.Charge
	}
	return 0
}

func (m *Particle) GetSpin() *XYZFloat {
	if m != nil {
		return m.Spin
	}
	return nil
}

type SimHit struct {
	// helper ID to circumvent volume lookup from global position during
	// digitization
	Volumeid uint64 `protobuf:"varint,1,opt,name=volumeid,proto3" json:"volumeid,omitempty"`
	// position in mm and time in ns
	Globalprepos *XYZTDouble `protobuf:"bytes,2,opt,name=globalprepos" json:"globalprepos,omitempty"`
	// position in mm and time in ns
	Globalpostpos *XYZTDouble `protobuf:"bytes,3,opt,name=globalpostpos" json:"globalpostpos,omitempty"`
	// energy in GeV
	Edep       float32 `protobuf:"fixed32,4,opt,name=edep,proto3" json:"edep,omitempty"`
	Particleid uint64  `protobuf:"varint,5,opt,name=particleid,proto3" json:"particleid,omitempty"`
}

func (m *SimHit) Reset()                    { *m = SimHit{} }
func (m *SimHit) String() string            { return proto.CompactTextString(m) }
func (*SimHit) ProtoMessage()               {}
func (*SimHit) Descriptor() ([]byte, []int) { return fileDescriptorEic, []int{7} }

func (m *SimHit) GetVolumeid() uint64 {
	if m != nil {
		return m.Volumeid
	}
	return 0
}

func (m *SimHit) GetGlobalprepos() *XYZTDouble {
	if m != nil {
		return m.Globalprepos
	}
	return nil
}

func (m *SimHit) GetGlobalpostpos() *XYZTDouble {
	if m != nil {
		return m.Globalpostpos
	}
	return nil
}

func (m *SimHit) GetEdep() float32 {
	if m != nil {
		return m.Edep
	}
	return 0
}

func (m *SimHit) GetParticleid() uint64 {
	if m != nil {
		return m.Particleid
	}
	return 0
}

func init() {
	proto.RegisterType((*XYZTInt)(nil), "proio.model.eic.XYZTInt")
	proto.RegisterType((*XYZTDouble)(nil), "proio.model.eic.XYZTDouble")
	proto.RegisterType((*XYZTFloat)(nil), "proio.model.eic.XYZTFloat")
	proto.RegisterType((*XYZInt)(nil), "proio.model.eic.XYZInt")
	proto.RegisterType((*XYZDouble)(nil), "proio.model.eic.XYZDouble")
	proto.RegisterType((*XYZFloat)(nil), "proio.model.eic.XYZFloat")
	proto.RegisterType((*Particle)(nil), "proio.model.eic.Particle")
	proto.RegisterType((*SimHit)(nil), "proio.model.eic.SimHit")
}
func (m *XYZTInt) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *XYZTInt) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.X != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintEic(dAtA, i, uint64((uint64(m.X)<<1)^uint64((m.X>>63))))
	}
	if m.Y != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintEic(dAtA, i, uint64((uint64(m.Y)<<1)^uint64((m.Y>>63))))
	}
	if m.Z != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintEic(dAtA, i, uint64((uint64(m.Z)<<1)^uint64((m.Z>>63))))
	}
	if m.T != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintEic(dAtA, i, uint64((uint64(m.T)<<1)^uint64((m.T>>63))))
	}
	return i, nil
}

func (m *XYZTDouble) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *XYZTDouble) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.X != 0 {
		dAtA[i] = 0x9
		i++
		i = encodeFixed64Eic(dAtA, i, uint64(math.Float64bits(float64(m.X))))
	}
	if m.Y != 0 {
		dAtA[i] = 0x11
		i++
		i = encodeFixed64Eic(dAtA, i, uint64(math.Float64bits(float64(m.Y))))
	}
	if m.Z != 0 {
		dAtA[i] = 0x19
		i++
		i = encodeFixed64Eic(dAtA, i, uint64(math.Float64bits(float64(m.Z))))
	}
	if m.T != 0 {
		dAtA[i] = 0x21
		i++
		i = encodeFixed64Eic(dAtA, i, uint64(math.Float64bits(float64(m.T))))
	}
	return i, nil
}

func (m *XYZTFloat) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *XYZTFloat) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.X != 0 {
		dAtA[i] = 0xd
		i++
		i = encodeFixed32Eic(dAtA, i, uint32(math.Float32bits(float32(m.X))))
	}
	if m.Y != 0 {
		dAtA[i] = 0x15
		i++
		i = encodeFixed32Eic(dAtA, i, uint32(math.Float32bits(float32(m.Y))))
	}
	if m.Z != 0 {
		dAtA[i] = 0x1d
		i++
		i = encodeFixed32Eic(dAtA, i, uint32(math.Float32bits(float32(m.Z))))
	}
	if m.T != 0 {
		dAtA[i] = 0x25
		i++
		i = encodeFixed32Eic(dAtA, i, uint32(math.Float32bits(float32(m.T))))
	}
	return i, nil
}

func (m *XYZInt) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *XYZInt) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.X != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintEic(dAtA, i, uint64((uint64(m.X)<<1)^uint64((m.X>>63))))
	}
	if m.Y != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintEic(dAtA, i, uint64((uint64(m.Y)<<1)^uint64((m.Y>>63))))
	}
	if m.Z != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintEic(dAtA, i, uint64((uint64(m.Z)<<1)^uint64((m.Z>>63))))
	}
	return i, nil
}

func (m *XYZDouble) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *XYZDouble) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.X != 0 {
		dAtA[i] = 0x9
		i++
		i = encodeFixed64Eic(dAtA, i, uint64(math.Float64bits(float64(m.X))))
	}
	if m.Y != 0 {
		dAtA[i] = 0x11
		i++
		i = encodeFixed64Eic(dAtA, i, uint64(math.Float64bits(float64(m.Y))))
	}
	if m.Z != 0 {
		dAtA[i] = 0x19
		i++
		i = encodeFixed64Eic(dAtA, i, uint64(math.Float64bits(float64(m.Z))))
	}
	return i, nil
}

func (m *XYZFloat) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *XYZFloat) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.X != 0 {
		dAtA[i] = 0xd
		i++
		i = encodeFixed32Eic(dAtA, i, uint32(math.Float32bits(float32(m.X))))
	}
	if m.Y != 0 {
		dAtA[i] = 0x15
		i++
		i = encodeFixed32Eic(dAtA, i, uint32(math.Float32bits(float32(m.Y))))
	}
	if m.Z != 0 {
		dAtA[i] = 0x1d
		i++
		i = encodeFixed32Eic(dAtA, i, uint32(math.Float32bits(float32(m.Z))))
	}
	return i, nil
}

func (m *Particle) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Particle) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Parent) > 0 {
		dAtA2 := make([]byte, len(m.Parent)*10)
		var j1 int
		for _, num := range m.Parent {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		dAtA[i] = 0xa
		i++
		i = encodeVarintEic(dAtA, i, uint64(j1))
		i += copy(dAtA[i:], dAtA2[:j1])
	}
	if len(m.Child) > 0 {
		dAtA4 := make([]byte, len(m.Child)*10)
		var j3 int
		for _, num := range m.Child {
			for num >= 1<<7 {
				dAtA4[j3] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j3++
			}
			dAtA4[j3] = uint8(num)
			j3++
		}
		dAtA[i] = 0x12
		i++
		i = encodeVarintEic(dAtA, i, uint64(j3))
		i += copy(dAtA[i:], dAtA4[:j3])
	}
	if m.Pdg != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintEic(dAtA, i, uint64((uint32(m.Pdg)<<1)^uint32((m.Pdg>>31))))
	}
	if m.Vertex != nil {
		dAtA[i] = 0x22
		i++
		i = encodeVarintEic(dAtA, i, uint64(m.Vertex.Size()))
		n5, err := m.Vertex.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n5
	}
	if m.P != nil {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintEic(dAtA, i, uint64(m.P.Size()))
		n6, err := m.P.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n6
	}
	if m.Mass != 0 {
		dAtA[i] = 0x31
		i++
		i = encodeFixed64Eic(dAtA, i, uint64(math.Float64bits(float64(m.Mass))))
	}
	if m.Charge != 0 {
		dAtA[i] = 0x3d
		i++
		i = encodeFixed32Eic(dAtA, i, uint32(math.Float32bits(float32(m.Charge))))
	}
	if m.Spin != nil {
		dAtA[i] = 0x42
		i++
		i = encodeVarintEic(dAtA, i, uint64(m.Spin.Size()))
		n7, err := m.Spin.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n7
	}
	return i, nil
}

func (m *SimHit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SimHit) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Volumeid != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintEic(dAtA, i, uint64(m.Volumeid))
	}
	if m.Globalprepos != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintEic(dAtA, i, uint64(m.Globalprepos.Size()))
		n8, err := m.Globalprepos.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n8
	}
	if m.Globalpostpos != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintEic(dAtA, i, uint64(m.Globalpostpos.Size()))
		n9, err := m.Globalpostpos.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n9
	}
	if m.Edep != 0 {
		dAtA[i] = 0x25
		i++
		i = encodeFixed32Eic(dAtA, i, uint32(math.Float32bits(float32(m.Edep))))
	}
	if m.Particleid != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintEic(dAtA, i, uint64(m.Particleid))
	}
	return i, nil
}

func encodeFixed64Eic(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Eic(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintEic(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *XYZTInt) Size() (n int) {
	var l int
	_ = l
	if m.X != 0 {
		n += 1 + sozEic(uint64(m.X))
	}
	if m.Y != 0 {
		n += 1 + sozEic(uint64(m.Y))
	}
	if m.Z != 0 {
		n += 1 + sozEic(uint64(m.Z))
	}
	if m.T != 0 {
		n += 1 + sozEic(uint64(m.T))
	}
	return n
}

func (m *XYZTDouble) Size() (n int) {
	var l int
	_ = l
	if m.X != 0 {
		n += 9
	}
	if m.Y != 0 {
		n += 9
	}
	if m.Z != 0 {
		n += 9
	}
	if m.T != 0 {
		n += 9
	}
	return n
}

func (m *XYZTFloat) Size() (n int) {
	var l int
	_ = l
	if m.X != 0 {
		n += 5
	}
	if m.Y != 0 {
		n += 5
	}
	if m.Z != 0 {
		n += 5
	}
	if m.T != 0 {
		n += 5
	}
	return n
}

func (m *XYZInt) Size() (n int) {
	var l int
	_ = l
	if m.X != 0 {
		n += 1 + sozEic(uint64(m.X))
	}
	if m.Y != 0 {
		n += 1 + sozEic(uint64(m.Y))
	}
	if m.Z != 0 {
		n += 1 + sozEic(uint64(m.Z))
	}
	return n
}

func (m *XYZDouble) Size() (n int) {
	var l int
	_ = l
	if m.X != 0 {
		n += 9
	}
	if m.Y != 0 {
		n += 9
	}
	if m.Z != 0 {
		n += 9
	}
	return n
}

func (m *XYZFloat) Size() (n int) {
	var l int
	_ = l
	if m.X != 0 {
		n += 5
	}
	if m.Y != 0 {
		n += 5
	}
	if m.Z != 0 {
		n += 5
	}
	return n
}

func (m *Particle) Size() (n int) {
	var l int
	_ = l
	if len(m.Parent) > 0 {
		l = 0
		for _, e := range m.Parent {
			l += sovEic(uint64(e))
		}
		n += 1 + sovEic(uint64(l)) + l
	}
	if len(m.Child) > 0 {
		l = 0
		for _, e := range m.Child {
			l += sovEic(uint64(e))
		}
		n += 1 + sovEic(uint64(l)) + l
	}
	if m.Pdg != 0 {
		n += 1 + sozEic(uint64(m.Pdg))
	}
	if m.Vertex != nil {
		l = m.Vertex.Size()
		n += 1 + l + sovEic(uint64(l))
	}
	if m.P != nil {
		l = m.P.Size()
		n += 1 + l + sovEic(uint64(l))
	}
	if m.Mass != 0 {
		n += 9
	}
	if m.Charge != 0 {
		n += 5
	}
	if m.Spin != nil {
		l = m.Spin.Size()
		n += 1 + l + sovEic(uint64(l))
	}
	return n
}

func (m *SimHit) Size() (n int) {
	var l int
	_ = l
	if m.Volumeid != 0 {
		n += 1 + sovEic(uint64(m.Volumeid))
	}
	if m.Globalprepos != nil {
		l = m.Globalprepos.Size()
		n += 1 + l + sovEic(uint64(l))
	}
	if m.Globalpostpos != nil {
		l = m.Globalpostpos.Size()
		n += 1 + l + sovEic(uint64(l))
	}
	if m.Edep != 0 {
		n += 5
	}
	if m.Particleid != 0 {
		n += 1 + sovEic(uint64(m.Particleid))
	}
	return n
}

func sovEic(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozEic(x uint64) (n int) {
	return sovEic(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *XYZTInt) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEic
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: XYZTInt: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: XYZTInt: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field X", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			v = (v >> 1) ^ uint64((int64(v&1)<<63)>>63)
			m.X = int64(v)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Y", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			v = (v >> 1) ^ uint64((int64(v&1)<<63)>>63)
			m.Y = int64(v)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Z", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			v = (v >> 1) ^ uint64((int64(v&1)<<63)>>63)
			m.Z = int64(v)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field T", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			v = (v >> 1) ^ uint64((int64(v&1)<<63)>>63)
			m.T = int64(v)
		default:
			iNdEx = preIndex
			skippy, err := skipEic(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEic
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *XYZTDouble) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEic
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: XYZTDouble: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: XYZTDouble: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field X", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 8
			v = uint64(dAtA[iNdEx-8])
			v |= uint64(dAtA[iNdEx-7]) << 8
			v |= uint64(dAtA[iNdEx-6]) << 16
			v |= uint64(dAtA[iNdEx-5]) << 24
			v |= uint64(dAtA[iNdEx-4]) << 32
			v |= uint64(dAtA[iNdEx-3]) << 40
			v |= uint64(dAtA[iNdEx-2]) << 48
			v |= uint64(dAtA[iNdEx-1]) << 56
			m.X = float64(math.Float64frombits(v))
		case 2:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Y", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 8
			v = uint64(dAtA[iNdEx-8])
			v |= uint64(dAtA[iNdEx-7]) << 8
			v |= uint64(dAtA[iNdEx-6]) << 16
			v |= uint64(dAtA[iNdEx-5]) << 24
			v |= uint64(dAtA[iNdEx-4]) << 32
			v |= uint64(dAtA[iNdEx-3]) << 40
			v |= uint64(dAtA[iNdEx-2]) << 48
			v |= uint64(dAtA[iNdEx-1]) << 56
			m.Y = float64(math.Float64frombits(v))
		case 3:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Z", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 8
			v = uint64(dAtA[iNdEx-8])
			v |= uint64(dAtA[iNdEx-7]) << 8
			v |= uint64(dAtA[iNdEx-6]) << 16
			v |= uint64(dAtA[iNdEx-5]) << 24
			v |= uint64(dAtA[iNdEx-4]) << 32
			v |= uint64(dAtA[iNdEx-3]) << 40
			v |= uint64(dAtA[iNdEx-2]) << 48
			v |= uint64(dAtA[iNdEx-1]) << 56
			m.Z = float64(math.Float64frombits(v))
		case 4:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field T", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 8
			v = uint64(dAtA[iNdEx-8])
			v |= uint64(dAtA[iNdEx-7]) << 8
			v |= uint64(dAtA[iNdEx-6]) << 16
			v |= uint64(dAtA[iNdEx-5]) << 24
			v |= uint64(dAtA[iNdEx-4]) << 32
			v |= uint64(dAtA[iNdEx-3]) << 40
			v |= uint64(dAtA[iNdEx-2]) << 48
			v |= uint64(dAtA[iNdEx-1]) << 56
			m.T = float64(math.Float64frombits(v))
		default:
			iNdEx = preIndex
			skippy, err := skipEic(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEic
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *XYZTFloat) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEic
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: XYZTFloat: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: XYZTFloat: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field X", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 4
			v = uint32(dAtA[iNdEx-4])
			v |= uint32(dAtA[iNdEx-3]) << 8
			v |= uint32(dAtA[iNdEx-2]) << 16
			v |= uint32(dAtA[iNdEx-1]) << 24
			m.X = float32(math.Float32frombits(v))
		case 2:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Y", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 4
			v = uint32(dAtA[iNdEx-4])
			v |= uint32(dAtA[iNdEx-3]) << 8
			v |= uint32(dAtA[iNdEx-2]) << 16
			v |= uint32(dAtA[iNdEx-1]) << 24
			m.Y = float32(math.Float32frombits(v))
		case 3:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Z", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 4
			v = uint32(dAtA[iNdEx-4])
			v |= uint32(dAtA[iNdEx-3]) << 8
			v |= uint32(dAtA[iNdEx-2]) << 16
			v |= uint32(dAtA[iNdEx-1]) << 24
			m.Z = float32(math.Float32frombits(v))
		case 4:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field T", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 4
			v = uint32(dAtA[iNdEx-4])
			v |= uint32(dAtA[iNdEx-3]) << 8
			v |= uint32(dAtA[iNdEx-2]) << 16
			v |= uint32(dAtA[iNdEx-1]) << 24
			m.T = float32(math.Float32frombits(v))
		default:
			iNdEx = preIndex
			skippy, err := skipEic(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEic
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *XYZInt) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEic
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: XYZInt: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: XYZInt: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field X", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			v = (v >> 1) ^ uint64((int64(v&1)<<63)>>63)
			m.X = int64(v)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Y", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			v = (v >> 1) ^ uint64((int64(v&1)<<63)>>63)
			m.Y = int64(v)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Z", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			v = (v >> 1) ^ uint64((int64(v&1)<<63)>>63)
			m.Z = int64(v)
		default:
			iNdEx = preIndex
			skippy, err := skipEic(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEic
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *XYZDouble) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEic
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: XYZDouble: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: XYZDouble: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field X", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 8
			v = uint64(dAtA[iNdEx-8])
			v |= uint64(dAtA[iNdEx-7]) << 8
			v |= uint64(dAtA[iNdEx-6]) << 16
			v |= uint64(dAtA[iNdEx-5]) << 24
			v |= uint64(dAtA[iNdEx-4]) << 32
			v |= uint64(dAtA[iNdEx-3]) << 40
			v |= uint64(dAtA[iNdEx-2]) << 48
			v |= uint64(dAtA[iNdEx-1]) << 56
			m.X = float64(math.Float64frombits(v))
		case 2:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Y", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 8
			v = uint64(dAtA[iNdEx-8])
			v |= uint64(dAtA[iNdEx-7]) << 8
			v |= uint64(dAtA[iNdEx-6]) << 16
			v |= uint64(dAtA[iNdEx-5]) << 24
			v |= uint64(dAtA[iNdEx-4]) << 32
			v |= uint64(dAtA[iNdEx-3]) << 40
			v |= uint64(dAtA[iNdEx-2]) << 48
			v |= uint64(dAtA[iNdEx-1]) << 56
			m.Y = float64(math.Float64frombits(v))
		case 3:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Z", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 8
			v = uint64(dAtA[iNdEx-8])
			v |= uint64(dAtA[iNdEx-7]) << 8
			v |= uint64(dAtA[iNdEx-6]) << 16
			v |= uint64(dAtA[iNdEx-5]) << 24
			v |= uint64(dAtA[iNdEx-4]) << 32
			v |= uint64(dAtA[iNdEx-3]) << 40
			v |= uint64(dAtA[iNdEx-2]) << 48
			v |= uint64(dAtA[iNdEx-1]) << 56
			m.Z = float64(math.Float64frombits(v))
		default:
			iNdEx = preIndex
			skippy, err := skipEic(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEic
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *XYZFloat) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEic
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: XYZFloat: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: XYZFloat: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field X", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 4
			v = uint32(dAtA[iNdEx-4])
			v |= uint32(dAtA[iNdEx-3]) << 8
			v |= uint32(dAtA[iNdEx-2]) << 16
			v |= uint32(dAtA[iNdEx-1]) << 24
			m.X = float32(math.Float32frombits(v))
		case 2:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Y", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 4
			v = uint32(dAtA[iNdEx-4])
			v |= uint32(dAtA[iNdEx-3]) << 8
			v |= uint32(dAtA[iNdEx-2]) << 16
			v |= uint32(dAtA[iNdEx-1]) << 24
			m.Y = float32(math.Float32frombits(v))
		case 3:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Z", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 4
			v = uint32(dAtA[iNdEx-4])
			v |= uint32(dAtA[iNdEx-3]) << 8
			v |= uint32(dAtA[iNdEx-2]) << 16
			v |= uint32(dAtA[iNdEx-1]) << 24
			m.Z = float32(math.Float32frombits(v))
		default:
			iNdEx = preIndex
			skippy, err := skipEic(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEic
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Particle) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEic
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Particle: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Particle: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowEic
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Parent = append(m.Parent, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowEic
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthEic
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowEic
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Parent = append(m.Parent, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Parent", wireType)
			}
		case 2:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowEic
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Child = append(m.Child, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowEic
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthEic
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowEic
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Child = append(m.Child, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Child", wireType)
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pdg", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			v = int32((uint32(v) >> 1) ^ uint32(((v&1)<<31)>>31))
			m.Pdg = v
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vertex", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEic
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Vertex == nil {
				m.Vertex = &XYZTDouble{}
			}
			if err := m.Vertex.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field P", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEic
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.P == nil {
				m.P = &XYZDouble{}
			}
			if err := m.P.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mass", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 8
			v = uint64(dAtA[iNdEx-8])
			v |= uint64(dAtA[iNdEx-7]) << 8
			v |= uint64(dAtA[iNdEx-6]) << 16
			v |= uint64(dAtA[iNdEx-5]) << 24
			v |= uint64(dAtA[iNdEx-4]) << 32
			v |= uint64(dAtA[iNdEx-3]) << 40
			v |= uint64(dAtA[iNdEx-2]) << 48
			v |= uint64(dAtA[iNdEx-1]) << 56
			m.Mass = float64(math.Float64frombits(v))
		case 7:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Charge", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 4
			v = uint32(dAtA[iNdEx-4])
			v |= uint32(dAtA[iNdEx-3]) << 8
			v |= uint32(dAtA[iNdEx-2]) << 16
			v |= uint32(dAtA[iNdEx-1]) << 24
			m.Charge = float32(math.Float32frombits(v))
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEic
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Spin == nil {
				m.Spin = &XYZFloat{}
			}
			if err := m.Spin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEic(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEic
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SimHit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEic
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SimHit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SimHit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Volumeid", wireType)
			}
			m.Volumeid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Volumeid |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Globalprepos", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEic
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Globalprepos == nil {
				m.Globalprepos = &XYZTDouble{}
			}
			if err := m.Globalprepos.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Globalpostpos", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEic
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Globalpostpos == nil {
				m.Globalpostpos = &XYZTDouble{}
			}
			if err := m.Globalpostpos.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Edep", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 4
			v = uint32(dAtA[iNdEx-4])
			v |= uint32(dAtA[iNdEx-3]) << 8
			v |= uint32(dAtA[iNdEx-2]) << 16
			v |= uint32(dAtA[iNdEx-1]) << 24
			m.Edep = float32(math.Float32frombits(v))
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Particleid", wireType)
			}
			m.Particleid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Particleid |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEic(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEic
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEic(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEic
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEic
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEic
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthEic
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowEic
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipEic(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthEic = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEic   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("proio/model/eic.proto", fileDescriptorEic) }

var fileDescriptorEic = []byte{
	// 461 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x59, 0xdb, 0x75, 0xc3, 0xb4, 0x08, 0x58, 0x01, 0x5a, 0x8a, 0x64, 0x55, 0x3e, 0xe5,
	0x52, 0x47, 0xb4, 0x70, 0x46, 0x2d, 0x05, 0xc1, 0x0d, 0x19, 0x90, 0x12, 0xdf, 0xec, 0xf5, 0xca,
	0x59, 0x69, 0x9d, 0x5d, 0xd9, 0x9b, 0x2a, 0xed, 0x99, 0x87, 0xe0, 0x91, 0x38, 0xf2, 0x00, 0x1c,
	0x50, 0x78, 0x11, 0xb4, 0x63, 0xab, 0x8d, 0xab, 0x4a, 0x55, 0x6e, 0xf3, 0x8f, 0xc6, 0xdf, 0xce,
	0xfc, 0xe3, 0x81, 0xe7, 0xa6, 0xd1, 0x52, 0x4f, 0x6a, 0x5d, 0x0a, 0x35, 0x11, 0x92, 0x27, 0xa6,
	0xd1, 0x56, 0xd3, 0xc7, 0x98, 0x4e, 0x30, 0x9d, 0x08, 0xc9, 0xe3, 0x53, 0xd8, 0x9d, 0xce, 0xb2,
	0x6f, 0x9f, 0x17, 0x96, 0xee, 0x03, 0x59, 0x31, 0x72, 0x48, 0xc6, 0x34, 0x25, 0x2b, 0xa7, 0x2e,
	0x99, 0xd7, 0xa9, 0x4b, 0xa7, 0xae, 0x98, 0xdf, 0xa9, 0x2b, 0xa7, 0x2c, 0x0b, 0x3a, 0x65, 0xe3,
	0x73, 0x00, 0x87, 0x38, 0xd7, 0xcb, 0x42, 0x89, 0x1b, 0x0a, 0x19, 0x50, 0xc8, 0x80, 0x42, 0x06,
	0x14, 0xe2, 0x28, 0xef, 0xe1, 0xa1, 0xa3, 0x7c, 0x54, 0x3a, 0xdf, 0x68, 0xc5, 0x1b, 0x40, 0xbc,
	0x01, 0xc4, 0x1b, 0x40, 0x3c, 0x07, 0x39, 0x86, 0x70, 0x3a, 0xcb, 0xb6, 0x1a, 0x26, 0x7e, 0x8b,
	0x0f, 0x6f, 0xdb, 0x7d, 0xfc, 0x06, 0x46, 0xd3, 0x59, 0xb6, 0x65, 0xbb, 0xf1, 0x0f, 0x0f, 0x46,
	0x5f, 0xf2, 0xc6, 0x4a, 0xae, 0x04, 0x7d, 0x01, 0xa1, 0xc9, 0x1b, 0xb1, 0xb0, 0x8c, 0x1c, 0xfa,
	0xe3, 0x20, 0xed, 0x15, 0x7d, 0x06, 0x3b, 0x7c, 0x2e, 0x55, 0xc9, 0x3c, 0x4c, 0x77, 0x82, 0x3e,
	0x01, 0xdf, 0x94, 0x15, 0xa2, 0x9e, 0xa6, 0x2e, 0xa4, 0x27, 0x10, 0x5e, 0x88, 0xc6, 0x8a, 0x15,
	0x1a, 0xb0, 0x77, 0xfc, 0x2a, 0xb9, 0xb5, 0xdd, 0xe4, 0x66, 0x2f, 0x69, 0x5f, 0x4a, 0xc7, 0x40,
	0x0c, 0xdb, 0xc1, 0xfa, 0x83, 0xbb, 0xea, 0xfb, 0x72, 0x62, 0x28, 0x85, 0xa0, 0xce, 0xdb, 0x96,
	0x85, 0x38, 0x32, 0xc6, 0xae, 0x65, 0x3e, 0xcf, 0x9b, 0x4a, 0xb0, 0x5d, 0x1c, 0xa9, 0x57, 0xf4,
	0x08, 0x82, 0xd6, 0xc8, 0x05, 0x1b, 0x21, 0xf8, 0xe5, 0x5d, 0x60, 0xb4, 0x2a, 0xc5, 0xb2, 0xf8,
	0x0f, 0x81, 0xf0, 0xab, 0xac, 0x3f, 0x49, 0x4b, 0x0f, 0x60, 0x74, 0xa1, 0xd5, 0xb2, 0x16, 0xb2,
	0x44, 0x0b, 0x83, 0xf4, 0x5a, 0xd3, 0x77, 0xb0, 0x5f, 0x29, 0x5d, 0xe4, 0xca, 0x34, 0xc2, 0xe8,
	0x16, 0x4d, 0xbd, 0x67, 0xcc, 0xc1, 0x07, 0xf4, 0x14, 0x1e, 0xf5, 0x5a, 0xb7, 0xd6, 0x11, 0xfc,
	0xfb, 0x09, 0xc3, 0x2f, 0x9c, 0x0b, 0xa2, 0x14, 0xa6, 0xff, 0xc7, 0x30, 0xa6, 0x11, 0x80, 0xe9,
	0x97, 0x28, 0x4b, 0x34, 0x33, 0x48, 0x37, 0x32, 0x67, 0xdf, 0x7f, 0xad, 0x23, 0xf2, 0x7b, 0x1d,
	0x91, 0xbf, 0xeb, 0x88, 0xfc, 0xfc, 0x17, 0x3d, 0x80, 0xbd, 0x8d, 0x07, 0xcf, 0xfc, 0x0f, 0x92,
	0x67, 0xaf, 0x2b, 0x69, 0xe7, 0xcb, 0x22, 0xe1, 0xba, 0x9e, 0x94, 0x82, 0xcb, 0x42, 0x28, 0xae,
	0xb5, 0x11, 0xcd, 0xa4, 0xbb, 0xdc, 0x4a, 0x1f, 0xdd, 0x3a, 0xe1, 0x22, 0xc4, 0x1b, 0x3e, 0xf9,
	0x1f, 0x00, 0x00, 0xff, 0xff, 0xf3, 0xf8, 0xd4, 0x06, 0xdc, 0x03, 0x00, 0x00,
}
