// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proio/model/eic.proto

package eic // import "github.com/decibelcooper/proio/go-proio/model/eic"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import encoding_binary "encoding/binary"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RandVar_Distribution int32

const (
	RandVar_NORMAL  RandVar_Distribution = 0
	RandVar_UNIFORM RandVar_Distribution = 1
)

var RandVar_Distribution_name = map[int32]string{
	0: "NORMAL",
	1: "UNIFORM",
}
var RandVar_Distribution_value = map[string]int32{
	"NORMAL":  0,
	"UNIFORM": 1,
}

func (x RandVar_Distribution) Enum() *RandVar_Distribution {
	p := new(RandVar_Distribution)
	*p = x
	return p
}
func (x RandVar_Distribution) String() string {
	return proto.EnumName(RandVar_Distribution_name, int32(x))
}
func (x *RandVar_Distribution) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RandVar_Distribution_value, data, "RandVar_Distribution")
	if err != nil {
		return err
	}
	*x = RandVar_Distribution(value)
	return nil
}
func (RandVar_Distribution) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eic_b0c1cfa6a8a64341, []int{6, 0}
}

type Particle struct {
	// ProIO entry identifiers that point to parent Particles
	Parent []uint64 `protobuf:"varint,1,rep,name=parent" json:"parent,omitempty"`
	// ProIO entry identifiers that point to child Particles
	Child []uint64 `protobuf:"varint,2,rep,name=child" json:"child,omitempty"`
	// PDG code
	Pdg *int32 `protobuf:"zigzag32,3,opt,name=pdg" json:"pdg,omitempty"`
	// position in mm and time in ns
	Vertex *XYZTD `protobuf:"bytes,4,opt,name=vertex" json:"vertex,omitempty"`
	// momentum in GeV
	P *XYZF `protobuf:"bytes,9,opt,name=p" json:"p,omitempty"`
	// mass in GeV
	Mass *float32 `protobuf:"fixed32,10,opt,name=mass" json:"mass,omitempty"`
	// charge in units of e
	Charge *float32 `protobuf:"fixed32,7,opt,name=charge" json:"charge,omitempty"`
	Spin   *XYZF    `protobuf:"bytes,8,opt,name=spin" json:"spin,omitempty"`
	// DEPRECATED
	PDouble              *XYZD    `protobuf:"bytes,5,opt,name=p_double,json=pDouble" json:"p_double,omitempty"`
	MassDouble           *float64 `protobuf:"fixed64,6,opt,name=mass_double,json=massDouble" json:"mass_double,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Particle) Reset()         { *m = Particle{} }
func (m *Particle) String() string { return proto.CompactTextString(m) }
func (*Particle) ProtoMessage()    {}
func (*Particle) Descriptor() ([]byte, []int) {
	return fileDescriptor_eic_b0c1cfa6a8a64341, []int{0}
}
func (m *Particle) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Particle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Particle.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Particle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Particle.Merge(dst, src)
}
func (m *Particle) XXX_Size() int {
	return m.Size()
}
func (m *Particle) XXX_DiscardUnknown() {
	xxx_messageInfo_Particle.DiscardUnknown(m)
}

var xxx_messageInfo_Particle proto.InternalMessageInfo

func (m *Particle) GetParent() []uint64 {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *Particle) GetChild() []uint64 {
	if m != nil {
		return m.Child
	}
	return nil
}

func (m *Particle) GetPdg() int32 {
	if m != nil && m.Pdg != nil {
		return *m.Pdg
	}
	return 0
}

func (m *Particle) GetVertex() *XYZTD {
	if m != nil {
		return m.Vertex
	}
	return nil
}

func (m *Particle) GetP() *XYZF {
	if m != nil {
		return m.P
	}
	return nil
}

func (m *Particle) GetMass() float32 {
	if m != nil && m.Mass != nil {
		return *m.Mass
	}
	return 0
}

func (m *Particle) GetCharge() float32 {
	if m != nil && m.Charge != nil {
		return *m.Charge
	}
	return 0
}

func (m *Particle) GetSpin() *XYZF {
	if m != nil {
		return m.Spin
	}
	return nil
}

func (m *Particle) GetPDouble() *XYZD {
	if m != nil {
		return m.PDouble
	}
	return nil
}

func (m *Particle) GetMassDouble() float64 {
	if m != nil && m.MassDouble != nil {
		return *m.MassDouble
	}
	return 0
}

type SimHit struct {
	// optional ID to circumvent volume lookup from global position during
	// digitization
	Volumeid *uint64 `protobuf:"varint,1,opt,name=volumeid" json:"volumeid,omitempty"`
	// spatial in mm and time in ns
	Globalprepos *XYZTD `protobuf:"bytes,2,opt,name=globalprepos" json:"globalprepos,omitempty"`
	// spatial in mm and time in ns
	Globalpostpos *XYZTD `protobuf:"bytes,3,opt,name=globalpostpos" json:"globalpostpos,omitempty"`
	// energy in GeV
	Edep *float32 `protobuf:"fixed32,4,opt,name=edep" json:"edep,omitempty"`
	// "particle" is a ProIO entry identifier that points to the Particle
	// responsible for this hit.
	Particle             *uint64  `protobuf:"varint,5,opt,name=particle" json:"particle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimHit) Reset()         { *m = SimHit{} }
func (m *SimHit) String() string { return proto.CompactTextString(m) }
func (*SimHit) ProtoMessage()    {}
func (*SimHit) Descriptor() ([]byte, []int) {
	return fileDescriptor_eic_b0c1cfa6a8a64341, []int{1}
}
func (m *SimHit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SimHit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SimHit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *SimHit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimHit.Merge(dst, src)
}
func (m *SimHit) XXX_Size() int {
	return m.Size()
}
func (m *SimHit) XXX_DiscardUnknown() {
	xxx_messageInfo_SimHit.DiscardUnknown(m)
}

var xxx_messageInfo_SimHit proto.InternalMessageInfo

func (m *SimHit) GetVolumeid() uint64 {
	if m != nil && m.Volumeid != nil {
		return *m.Volumeid
	}
	return 0
}

func (m *SimHit) GetGlobalprepos() *XYZTD {
	if m != nil {
		return m.Globalprepos
	}
	return nil
}

func (m *SimHit) GetGlobalpostpos() *XYZTD {
	if m != nil {
		return m.Globalpostpos
	}
	return nil
}

func (m *SimHit) GetEdep() float32 {
	if m != nil && m.Edep != nil {
		return *m.Edep
	}
	return 0
}

func (m *SimHit) GetParticle() uint64 {
	if m != nil && m.Particle != nil {
		return *m.Particle
	}
	return 0
}

type EnergyDep struct {
	// mean and noise are in units of GeV
	Mean *float32 `protobuf:"fixed32,1,opt,name=mean" json:"mean,omitempty"`
	// sigma value for normally-distributed noise
	Noise *float32 `protobuf:"fixed32,2,opt,name=noise" json:"noise,omitempty"`
	// Multiple possible positions can be specified.
	Pos []*ObservedPos `protobuf:"bytes,3,rep,name=pos" json:"pos,omitempty"`
	// "source"s are ProIO entry identifiers that may point to SimHits,
	// Particles, or specialized raw data objects.
	Source               []uint64 `protobuf:"varint,4,rep,name=source" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnergyDep) Reset()         { *m = EnergyDep{} }
func (m *EnergyDep) String() string { return proto.CompactTextString(m) }
func (*EnergyDep) ProtoMessage()    {}
func (*EnergyDep) Descriptor() ([]byte, []int) {
	return fileDescriptor_eic_b0c1cfa6a8a64341, []int{2}
}
func (m *EnergyDep) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EnergyDep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EnergyDep.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *EnergyDep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnergyDep.Merge(dst, src)
}
func (m *EnergyDep) XXX_Size() int {
	return m.Size()
}
func (m *EnergyDep) XXX_DiscardUnknown() {
	xxx_messageInfo_EnergyDep.DiscardUnknown(m)
}

var xxx_messageInfo_EnergyDep proto.InternalMessageInfo

func (m *EnergyDep) GetMean() float32 {
	if m != nil && m.Mean != nil {
		return *m.Mean
	}
	return 0
}

func (m *EnergyDep) GetNoise() float32 {
	if m != nil && m.Noise != nil {
		return *m.Noise
	}
	return 0
}

func (m *EnergyDep) GetPos() []*ObservedPos {
	if m != nil {
		return m.Pos
	}
	return nil
}

func (m *EnergyDep) GetSource() []uint64 {
	if m != nil {
		return m.Source
	}
	return nil
}

type Track struct {
	Segment              []*TrackSegment `protobuf:"bytes,1,rep,name=segment" json:"segment,omitempty"`
	Observation          []uint64        `protobuf:"varint,2,rep,name=observation" json:"observation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Track) Reset()         { *m = Track{} }
func (m *Track) String() string { return proto.CompactTextString(m) }
func (*Track) ProtoMessage()    {}
func (*Track) Descriptor() ([]byte, []int) {
	return fileDescriptor_eic_b0c1cfa6a8a64341, []int{3}
}
func (m *Track) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Track) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Track.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Track) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Track.Merge(dst, src)
}
func (m *Track) XXX_Size() int {
	return m.Size()
}
func (m *Track) XXX_DiscardUnknown() {
	xxx_messageInfo_Track.DiscardUnknown(m)
}

var xxx_messageInfo_Track proto.InternalMessageInfo

func (m *Track) GetSegment() []*TrackSegment {
	if m != nil {
		return m.Segment
	}
	return nil
}

func (m *Track) GetObservation() []uint64 {
	if m != nil {
		return m.Observation
	}
	return nil
}

type TrackSegment struct {
	// start of segment in mm/ns
	Vertex      *XYZTD     `protobuf:"bytes,1,opt,name=vertex" json:"vertex,omitempty"`
	Vertexnoise []*RandVar `protobuf:"bytes,2,rep,name=vertexnoise" json:"vertexnoise,omitempty"`
	// momentum normalized to the magnitude of the charge (GeV)
	Poq      *XYZD      `protobuf:"bytes,3,opt,name=poq" json:"poq,omitempty"`
	Poqnoise []*RandVar `protobuf:"bytes,4,rep,name=poqnoise" json:"poqnoise,omitempty"`
	// magnetic field at the vertex (T)
	Magfield *XYZD `protobuf:"bytes,9,opt,name=magfield" json:"magfield,omitempty"`
	// sign of the track charge
	Chargesign *float32 `protobuf:"fixed32,7,opt,name=chargesign" json:"chargesign,omitempty"`
	// length of the segment in mm
	Length *float32 `protobuf:"fixed32,8,opt,name=length" json:"length,omitempty"`
	// DEPRECATED
	Curvature            *XYZD      `protobuf:"bytes,5,opt,name=curvature" json:"curvature,omitempty"`
	Curvaturenoise       []*RandVar `protobuf:"bytes,6,rep,name=curvaturenoise" json:"curvaturenoise,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TrackSegment) Reset()         { *m = TrackSegment{} }
func (m *TrackSegment) String() string { return proto.CompactTextString(m) }
func (*TrackSegment) ProtoMessage()    {}
func (*TrackSegment) Descriptor() ([]byte, []int) {
	return fileDescriptor_eic_b0c1cfa6a8a64341, []int{4}
}
func (m *TrackSegment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TrackSegment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TrackSegment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *TrackSegment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackSegment.Merge(dst, src)
}
func (m *TrackSegment) XXX_Size() int {
	return m.Size()
}
func (m *TrackSegment) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackSegment.DiscardUnknown(m)
}

var xxx_messageInfo_TrackSegment proto.InternalMessageInfo

func (m *TrackSegment) GetVertex() *XYZTD {
	if m != nil {
		return m.Vertex
	}
	return nil
}

func (m *TrackSegment) GetVertexnoise() []*RandVar {
	if m != nil {
		return m.Vertexnoise
	}
	return nil
}

func (m *TrackSegment) GetPoq() *XYZD {
	if m != nil {
		return m.Poq
	}
	return nil
}

func (m *TrackSegment) GetPoqnoise() []*RandVar {
	if m != nil {
		return m.Poqnoise
	}
	return nil
}

func (m *TrackSegment) GetMagfield() *XYZD {
	if m != nil {
		return m.Magfield
	}
	return nil
}

func (m *TrackSegment) GetChargesign() float32 {
	if m != nil && m.Chargesign != nil {
		return *m.Chargesign
	}
	return 0
}

func (m *TrackSegment) GetLength() float32 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *TrackSegment) GetCurvature() *XYZD {
	if m != nil {
		return m.Curvature
	}
	return nil
}

func (m *TrackSegment) GetCurvaturenoise() []*RandVar {
	if m != nil {
		return m.Curvaturenoise
	}
	return nil
}

// position with detailed noise
type ObservedPos struct {
	// spatial in mm and time in ns
	Mean *XYZTD `protobuf:"bytes,1,opt,name=mean" json:"mean,omitempty"`
	// These RandVars describe independent random noise contributions, and
	// repeated RandVars imply addition, or alternatively a convolution of
	// their distributions.  The contributions must combine to span the full
	// 4-dimensional space, so the number of contributions must be >= 4.
	Noise []*RandVar `protobuf:"bytes,2,rep,name=noise" json:"noise,omitempty"`
	// "weightmod" describes additional weight to be applied to this position.
	// For the case of multiple possible positions, it is implied that by
	// default each position is equally likely.  This can be changed by adding
	// weight to positions.  To make one position twice as likely as a position
	// without a weight modifier, set weightmod to +1.
	Weightmod            *float32 `protobuf:"fixed32,3,opt,name=weightmod" json:"weightmod,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObservedPos) Reset()         { *m = ObservedPos{} }
func (m *ObservedPos) String() string { return proto.CompactTextString(m) }
func (*ObservedPos) ProtoMessage()    {}
func (*ObservedPos) Descriptor() ([]byte, []int) {
	return fileDescriptor_eic_b0c1cfa6a8a64341, []int{5}
}
func (m *ObservedPos) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ObservedPos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ObservedPos.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *ObservedPos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObservedPos.Merge(dst, src)
}
func (m *ObservedPos) XXX_Size() int {
	return m.Size()
}
func (m *ObservedPos) XXX_DiscardUnknown() {
	xxx_messageInfo_ObservedPos.DiscardUnknown(m)
}

var xxx_messageInfo_ObservedPos proto.InternalMessageInfo

func (m *ObservedPos) GetMean() *XYZTD {
	if m != nil {
		return m.Mean
	}
	return nil
}

func (m *ObservedPos) GetNoise() []*RandVar {
	if m != nil {
		return m.Noise
	}
	return nil
}

func (m *ObservedPos) GetWeightmod() float32 {
	if m != nil && m.Weightmod != nil {
		return *m.Weightmod
	}
	return 0
}

// random variable with a specified distribution along an axis defined in XYZT
type RandVar struct {
	Dist *RandVar_Distribution `protobuf:"varint,2,opt,name=dist,enum=proio.model.eic.RandVar_Distribution" json:"dist,omitempty"`
	// spatial in mm and time in ns
	Sigma                *XYZTF   `protobuf:"bytes,3,opt,name=sigma" json:"sigma,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RandVar) Reset()         { *m = RandVar{} }
func (m *RandVar) String() string { return proto.CompactTextString(m) }
func (*RandVar) ProtoMessage()    {}
func (*RandVar) Descriptor() ([]byte, []int) {
	return fileDescriptor_eic_b0c1cfa6a8a64341, []int{6}
}
func (m *RandVar) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RandVar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RandVar.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *RandVar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RandVar.Merge(dst, src)
}
func (m *RandVar) XXX_Size() int {
	return m.Size()
}
func (m *RandVar) XXX_DiscardUnknown() {
	xxx_messageInfo_RandVar.DiscardUnknown(m)
}

var xxx_messageInfo_RandVar proto.InternalMessageInfo

func (m *RandVar) GetDist() RandVar_Distribution {
	if m != nil && m.Dist != nil {
		return *m.Dist
	}
	return RandVar_NORMAL
}

func (m *RandVar) GetSigma() *XYZTF {
	if m != nil {
		return m.Sigma
	}
	return nil
}

type XYZTD struct {
	X                    *float64 `protobuf:"fixed64,1,opt,name=x" json:"x,omitempty"`
	Y                    *float64 `protobuf:"fixed64,2,opt,name=y" json:"y,omitempty"`
	Z                    *float64 `protobuf:"fixed64,3,opt,name=z" json:"z,omitempty"`
	T                    *float64 `protobuf:"fixed64,4,opt,name=t" json:"t,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XYZTD) Reset()         { *m = XYZTD{} }
func (m *XYZTD) String() string { return proto.CompactTextString(m) }
func (*XYZTD) ProtoMessage()    {}
func (*XYZTD) Descriptor() ([]byte, []int) {
	return fileDescriptor_eic_b0c1cfa6a8a64341, []int{7}
}
func (m *XYZTD) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *XYZTD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_XYZTD.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *XYZTD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XYZTD.Merge(dst, src)
}
func (m *XYZTD) XXX_Size() int {
	return m.Size()
}
func (m *XYZTD) XXX_DiscardUnknown() {
	xxx_messageInfo_XYZTD.DiscardUnknown(m)
}

var xxx_messageInfo_XYZTD proto.InternalMessageInfo

func (m *XYZTD) GetX() float64 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *XYZTD) GetY() float64 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *XYZTD) GetZ() float64 {
	if m != nil && m.Z != nil {
		return *m.Z
	}
	return 0
}

func (m *XYZTD) GetT() float64 {
	if m != nil && m.T != nil {
		return *m.T
	}
	return 0
}

type XYZTF struct {
	X                    *float32 `protobuf:"fixed32,1,opt,name=x" json:"x,omitempty"`
	Y                    *float32 `protobuf:"fixed32,2,opt,name=y" json:"y,omitempty"`
	Z                    *float32 `protobuf:"fixed32,3,opt,name=z" json:"z,omitempty"`
	T                    *float32 `protobuf:"fixed32,4,opt,name=t" json:"t,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XYZTF) Reset()         { *m = XYZTF{} }
func (m *XYZTF) String() string { return proto.CompactTextString(m) }
func (*XYZTF) ProtoMessage()    {}
func (*XYZTF) Descriptor() ([]byte, []int) {
	return fileDescriptor_eic_b0c1cfa6a8a64341, []int{8}
}
func (m *XYZTF) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *XYZTF) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_XYZTF.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *XYZTF) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XYZTF.Merge(dst, src)
}
func (m *XYZTF) XXX_Size() int {
	return m.Size()
}
func (m *XYZTF) XXX_DiscardUnknown() {
	xxx_messageInfo_XYZTF.DiscardUnknown(m)
}

var xxx_messageInfo_XYZTF proto.InternalMessageInfo

func (m *XYZTF) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *XYZTF) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *XYZTF) GetZ() float32 {
	if m != nil && m.Z != nil {
		return *m.Z
	}
	return 0
}

func (m *XYZTF) GetT() float32 {
	if m != nil && m.T != nil {
		return *m.T
	}
	return 0
}

type XYZD struct {
	X                    *float64 `protobuf:"fixed64,1,opt,name=x" json:"x,omitempty"`
	Y                    *float64 `protobuf:"fixed64,2,opt,name=y" json:"y,omitempty"`
	Z                    *float64 `protobuf:"fixed64,3,opt,name=z" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XYZD) Reset()         { *m = XYZD{} }
func (m *XYZD) String() string { return proto.CompactTextString(m) }
func (*XYZD) ProtoMessage()    {}
func (*XYZD) Descriptor() ([]byte, []int) {
	return fileDescriptor_eic_b0c1cfa6a8a64341, []int{9}
}
func (m *XYZD) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *XYZD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_XYZD.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *XYZD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XYZD.Merge(dst, src)
}
func (m *XYZD) XXX_Size() int {
	return m.Size()
}
func (m *XYZD) XXX_DiscardUnknown() {
	xxx_messageInfo_XYZD.DiscardUnknown(m)
}

var xxx_messageInfo_XYZD proto.InternalMessageInfo

func (m *XYZD) GetX() float64 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *XYZD) GetY() float64 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *XYZD) GetZ() float64 {
	if m != nil && m.Z != nil {
		return *m.Z
	}
	return 0
}

type XYZF struct {
	X                    *float32 `protobuf:"fixed32,1,opt,name=x" json:"x,omitempty"`
	Y                    *float32 `protobuf:"fixed32,2,opt,name=y" json:"y,omitempty"`
	Z                    *float32 `protobuf:"fixed32,3,opt,name=z" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XYZF) Reset()         { *m = XYZF{} }
func (m *XYZF) String() string { return proto.CompactTextString(m) }
func (*XYZF) ProtoMessage()    {}
func (*XYZF) Descriptor() ([]byte, []int) {
	return fileDescriptor_eic_b0c1cfa6a8a64341, []int{10}
}
func (m *XYZF) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *XYZF) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_XYZF.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *XYZF) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XYZF.Merge(dst, src)
}
func (m *XYZF) XXX_Size() int {
	return m.Size()
}
func (m *XYZF) XXX_DiscardUnknown() {
	xxx_messageInfo_XYZF.DiscardUnknown(m)
}

var xxx_messageInfo_XYZF proto.InternalMessageInfo

func (m *XYZF) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *XYZF) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *XYZF) GetZ() float32 {
	if m != nil && m.Z != nil {
		return *m.Z
	}
	return 0
}

func init() {
	proto.RegisterType((*Particle)(nil), "proio.model.eic.Particle")
	proto.RegisterType((*SimHit)(nil), "proio.model.eic.SimHit")
	proto.RegisterType((*EnergyDep)(nil), "proio.model.eic.EnergyDep")
	proto.RegisterType((*Track)(nil), "proio.model.eic.Track")
	proto.RegisterType((*TrackSegment)(nil), "proio.model.eic.TrackSegment")
	proto.RegisterType((*ObservedPos)(nil), "proio.model.eic.ObservedPos")
	proto.RegisterType((*RandVar)(nil), "proio.model.eic.RandVar")
	proto.RegisterType((*XYZTD)(nil), "proio.model.eic.XYZTD")
	proto.RegisterType((*XYZTF)(nil), "proio.model.eic.XYZTF")
	proto.RegisterType((*XYZD)(nil), "proio.model.eic.XYZD")
	proto.RegisterType((*XYZF)(nil), "proio.model.eic.XYZF")
	proto.RegisterEnum("proio.model.eic.RandVar_Distribution", RandVar_Distribution_name, RandVar_Distribution_value)
}
func (m *Particle) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Particle) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Parent) > 0 {
		for _, num := range m.Parent {
			dAtA[i] = 0x8
			i++
			i = encodeVarintEic(dAtA, i, uint64(num))
		}
	}
	if len(m.Child) > 0 {
		for _, num := range m.Child {
			dAtA[i] = 0x10
			i++
			i = encodeVarintEic(dAtA, i, uint64(num))
		}
	}
	if m.Pdg != nil {
		dAtA[i] = 0x18
		i++
		i = encodeVarintEic(dAtA, i, uint64((uint32(*m.Pdg)<<1)^uint32((*m.Pdg>>31))))
	}
	if m.Vertex != nil {
		dAtA[i] = 0x22
		i++
		i = encodeVarintEic(dAtA, i, uint64(m.Vertex.Size()))
		n1, err := m.Vertex.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.PDouble != nil {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintEic(dAtA, i, uint64(m.PDouble.Size()))
		n2, err := m.PDouble.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if m.MassDouble != nil {
		dAtA[i] = 0x31
		i++
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(*m.MassDouble))))
		i += 8
	}
	if m.Charge != nil {
		dAtA[i] = 0x3d
		i++
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(*m.Charge))))
		i += 4
	}
	if m.Spin != nil {
		dAtA[i] = 0x42
		i++
		i = encodeVarintEic(dAtA, i, uint64(m.Spin.Size()))
		n3, err := m.Spin.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	if m.P != nil {
		dAtA[i] = 0x4a
		i++
		i = encodeVarintEic(dAtA, i, uint64(m.P.Size()))
		n4, err := m.P.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n4
	}
	if m.Mass != nil {
		dAtA[i] = 0x55
		i++
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(*m.Mass))))
		i += 4
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *SimHit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SimHit) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Volumeid != nil {
		dAtA[i] = 0x8
		i++
		i = encodeVarintEic(dAtA, i, uint64(*m.Volumeid))
	}
	if m.Globalprepos != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintEic(dAtA, i, uint64(m.Globalprepos.Size()))
		n5, err := m.Globalprepos.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n5
	}
	if m.Globalpostpos != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintEic(dAtA, i, uint64(m.Globalpostpos.Size()))
		n6, err := m.Globalpostpos.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n6
	}
	if m.Edep != nil {
		dAtA[i] = 0x25
		i++
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(*m.Edep))))
		i += 4
	}
	if m.Particle != nil {
		dAtA[i] = 0x28
		i++
		i = encodeVarintEic(dAtA, i, uint64(*m.Particle))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *EnergyDep) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EnergyDep) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Mean != nil {
		dAtA[i] = 0xd
		i++
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(*m.Mean))))
		i += 4
	}
	if m.Noise != nil {
		dAtA[i] = 0x15
		i++
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(*m.Noise))))
		i += 4
	}
	if len(m.Pos) > 0 {
		for _, msg := range m.Pos {
			dAtA[i] = 0x1a
			i++
			i = encodeVarintEic(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.Source) > 0 {
		for _, num := range m.Source {
			dAtA[i] = 0x20
			i++
			i = encodeVarintEic(dAtA, i, uint64(num))
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *Track) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Track) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Segment) > 0 {
		for _, msg := range m.Segment {
			dAtA[i] = 0xa
			i++
			i = encodeVarintEic(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.Observation) > 0 {
		for _, num := range m.Observation {
			dAtA[i] = 0x10
			i++
			i = encodeVarintEic(dAtA, i, uint64(num))
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *TrackSegment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TrackSegment) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Vertex != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintEic(dAtA, i, uint64(m.Vertex.Size()))
		n7, err := m.Vertex.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n7
	}
	if len(m.Vertexnoise) > 0 {
		for _, msg := range m.Vertexnoise {
			dAtA[i] = 0x12
			i++
			i = encodeVarintEic(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.Poq != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintEic(dAtA, i, uint64(m.Poq.Size()))
		n8, err := m.Poq.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n8
	}
	if len(m.Poqnoise) > 0 {
		for _, msg := range m.Poqnoise {
			dAtA[i] = 0x22
			i++
			i = encodeVarintEic(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.Curvature != nil {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintEic(dAtA, i, uint64(m.Curvature.Size()))
		n9, err := m.Curvature.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n9
	}
	if len(m.Curvaturenoise) > 0 {
		for _, msg := range m.Curvaturenoise {
			dAtA[i] = 0x32
			i++
			i = encodeVarintEic(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.Chargesign != nil {
		dAtA[i] = 0x3d
		i++
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(*m.Chargesign))))
		i += 4
	}
	if m.Length != nil {
		dAtA[i] = 0x45
		i++
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(*m.Length))))
		i += 4
	}
	if m.Magfield != nil {
		dAtA[i] = 0x4a
		i++
		i = encodeVarintEic(dAtA, i, uint64(m.Magfield.Size()))
		n10, err := m.Magfield.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n10
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ObservedPos) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ObservedPos) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Mean != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintEic(dAtA, i, uint64(m.Mean.Size()))
		n11, err := m.Mean.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n11
	}
	if len(m.Noise) > 0 {
		for _, msg := range m.Noise {
			dAtA[i] = 0x12
			i++
			i = encodeVarintEic(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.Weightmod != nil {
		dAtA[i] = 0x1d
		i++
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(*m.Weightmod))))
		i += 4
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *RandVar) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RandVar) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Dist != nil {
		dAtA[i] = 0x10
		i++
		i = encodeVarintEic(dAtA, i, uint64(*m.Dist))
	}
	if m.Sigma != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintEic(dAtA, i, uint64(m.Sigma.Size()))
		n12, err := m.Sigma.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n12
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *XYZTD) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *XYZTD) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.X != nil {
		dAtA[i] = 0x9
		i++
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(*m.X))))
		i += 8
	}
	if m.Y != nil {
		dAtA[i] = 0x11
		i++
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(*m.Y))))
		i += 8
	}
	if m.Z != nil {
		dAtA[i] = 0x19
		i++
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(*m.Z))))
		i += 8
	}
	if m.T != nil {
		dAtA[i] = 0x21
		i++
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(*m.T))))
		i += 8
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *XYZTF) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *XYZTF) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.X != nil {
		dAtA[i] = 0xd
		i++
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(*m.X))))
		i += 4
	}
	if m.Y != nil {
		dAtA[i] = 0x15
		i++
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(*m.Y))))
		i += 4
	}
	if m.Z != nil {
		dAtA[i] = 0x1d
		i++
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(*m.Z))))
		i += 4
	}
	if m.T != nil {
		dAtA[i] = 0x25
		i++
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(*m.T))))
		i += 4
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *XYZD) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *XYZD) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.X != nil {
		dAtA[i] = 0x9
		i++
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(*m.X))))
		i += 8
	}
	if m.Y != nil {
		dAtA[i] = 0x11
		i++
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(*m.Y))))
		i += 8
	}
	if m.Z != nil {
		dAtA[i] = 0x19
		i++
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(*m.Z))))
		i += 8
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *XYZF) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *XYZF) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.X != nil {
		dAtA[i] = 0xd
		i++
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(*m.X))))
		i += 4
	}
	if m.Y != nil {
		dAtA[i] = 0x15
		i++
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(*m.Y))))
		i += 4
	}
	if m.Z != nil {
		dAtA[i] = 0x1d
		i++
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(*m.Z))))
		i += 4
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintEic(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Particle) Size() (n int) {
	var l int
	_ = l
	if len(m.Parent) > 0 {
		for _, e := range m.Parent {
			n += 1 + sovEic(uint64(e))
		}
	}
	if len(m.Child) > 0 {
		for _, e := range m.Child {
			n += 1 + sovEic(uint64(e))
		}
	}
	if m.Pdg != nil {
		n += 1 + sozEic(uint64(*m.Pdg))
	}
	if m.Vertex != nil {
		l = m.Vertex.Size()
		n += 1 + l + sovEic(uint64(l))
	}
	if m.PDouble != nil {
		l = m.PDouble.Size()
		n += 1 + l + sovEic(uint64(l))
	}
	if m.MassDouble != nil {
		n += 9
	}
	if m.Charge != nil {
		n += 5
	}
	if m.Spin != nil {
		l = m.Spin.Size()
		n += 1 + l + sovEic(uint64(l))
	}
	if m.P != nil {
		l = m.P.Size()
		n += 1 + l + sovEic(uint64(l))
	}
	if m.Mass != nil {
		n += 5
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SimHit) Size() (n int) {
	var l int
	_ = l
	if m.Volumeid != nil {
		n += 1 + sovEic(uint64(*m.Volumeid))
	}
	if m.Globalprepos != nil {
		l = m.Globalprepos.Size()
		n += 1 + l + sovEic(uint64(l))
	}
	if m.Globalpostpos != nil {
		l = m.Globalpostpos.Size()
		n += 1 + l + sovEic(uint64(l))
	}
	if m.Edep != nil {
		n += 5
	}
	if m.Particle != nil {
		n += 1 + sovEic(uint64(*m.Particle))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *EnergyDep) Size() (n int) {
	var l int
	_ = l
	if m.Mean != nil {
		n += 5
	}
	if m.Noise != nil {
		n += 5
	}
	if len(m.Pos) > 0 {
		for _, e := range m.Pos {
			l = e.Size()
			n += 1 + l + sovEic(uint64(l))
		}
	}
	if len(m.Source) > 0 {
		for _, e := range m.Source {
			n += 1 + sovEic(uint64(e))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Track) Size() (n int) {
	var l int
	_ = l
	if len(m.Segment) > 0 {
		for _, e := range m.Segment {
			l = e.Size()
			n += 1 + l + sovEic(uint64(l))
		}
	}
	if len(m.Observation) > 0 {
		for _, e := range m.Observation {
			n += 1 + sovEic(uint64(e))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *TrackSegment) Size() (n int) {
	var l int
	_ = l
	if m.Vertex != nil {
		l = m.Vertex.Size()
		n += 1 + l + sovEic(uint64(l))
	}
	if len(m.Vertexnoise) > 0 {
		for _, e := range m.Vertexnoise {
			l = e.Size()
			n += 1 + l + sovEic(uint64(l))
		}
	}
	if m.Poq != nil {
		l = m.Poq.Size()
		n += 1 + l + sovEic(uint64(l))
	}
	if len(m.Poqnoise) > 0 {
		for _, e := range m.Poqnoise {
			l = e.Size()
			n += 1 + l + sovEic(uint64(l))
		}
	}
	if m.Curvature != nil {
		l = m.Curvature.Size()
		n += 1 + l + sovEic(uint64(l))
	}
	if len(m.Curvaturenoise) > 0 {
		for _, e := range m.Curvaturenoise {
			l = e.Size()
			n += 1 + l + sovEic(uint64(l))
		}
	}
	if m.Chargesign != nil {
		n += 5
	}
	if m.Length != nil {
		n += 5
	}
	if m.Magfield != nil {
		l = m.Magfield.Size()
		n += 1 + l + sovEic(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ObservedPos) Size() (n int) {
	var l int
	_ = l
	if m.Mean != nil {
		l = m.Mean.Size()
		n += 1 + l + sovEic(uint64(l))
	}
	if len(m.Noise) > 0 {
		for _, e := range m.Noise {
			l = e.Size()
			n += 1 + l + sovEic(uint64(l))
		}
	}
	if m.Weightmod != nil {
		n += 5
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *RandVar) Size() (n int) {
	var l int
	_ = l
	if m.Dist != nil {
		n += 1 + sovEic(uint64(*m.Dist))
	}
	if m.Sigma != nil {
		l = m.Sigma.Size()
		n += 1 + l + sovEic(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *XYZTD) Size() (n int) {
	var l int
	_ = l
	if m.X != nil {
		n += 9
	}
	if m.Y != nil {
		n += 9
	}
	if m.Z != nil {
		n += 9
	}
	if m.T != nil {
		n += 9
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *XYZTF) Size() (n int) {
	var l int
	_ = l
	if m.X != nil {
		n += 5
	}
	if m.Y != nil {
		n += 5
	}
	if m.Z != nil {
		n += 5
	}
	if m.T != nil {
		n += 5
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *XYZD) Size() (n int) {
	var l int
	_ = l
	if m.X != nil {
		n += 9
	}
	if m.Y != nil {
		n += 9
	}
	if m.Z != nil {
		n += 9
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *XYZF) Size() (n int) {
	var l int
	_ = l
	if m.X != nil {
		n += 5
	}
	if m.Y != nil {
		n += 5
	}
	if m.Z != nil {
		n += 5
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovEic(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozEic(x uint64) (n int) {
	return sovEic(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Particle) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEic
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Particle: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Particle: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowEic
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Parent = append(m.Parent, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowEic
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthEic
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowEic
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Parent = append(m.Parent, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Parent", wireType)
			}
		case 2:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowEic
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Child = append(m.Child, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowEic
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthEic
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowEic
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Child = append(m.Child, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Child", wireType)
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pdg", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			v = int32((uint32(v) >> 1) ^ uint32(((v&1)<<31)>>31))
			m.Pdg = &v
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vertex", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEic
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Vertex == nil {
				m.Vertex = &XYZTD{}
			}
			if err := m.Vertex.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PDouble", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEic
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PDouble == nil {
				m.PDouble = &XYZD{}
			}
			if err := m.PDouble.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field MassDouble", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			v2 := float64(math.Float64frombits(v))
			m.MassDouble = &v2
		case 7:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Charge", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			v2 := float32(math.Float32frombits(v))
			m.Charge = &v2
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEic
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Spin == nil {
				m.Spin = &XYZF{}
			}
			if err := m.Spin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field P", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEic
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.P == nil {
				m.P = &XYZF{}
			}
			if err := m.P.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mass", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			v2 := float32(math.Float32frombits(v))
			m.Mass = &v2
		default:
			iNdEx = preIndex
			skippy, err := skipEic(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEic
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SimHit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEic
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SimHit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SimHit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Volumeid", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Volumeid = &v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Globalprepos", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEic
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Globalprepos == nil {
				m.Globalprepos = &XYZTD{}
			}
			if err := m.Globalprepos.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Globalpostpos", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEic
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Globalpostpos == nil {
				m.Globalpostpos = &XYZTD{}
			}
			if err := m.Globalpostpos.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Edep", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			v2 := float32(math.Float32frombits(v))
			m.Edep = &v2
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Particle", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Particle = &v
		default:
			iNdEx = preIndex
			skippy, err := skipEic(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEic
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EnergyDep) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEic
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EnergyDep: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EnergyDep: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mean", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			v2 := float32(math.Float32frombits(v))
			m.Mean = &v2
		case 2:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Noise", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			v2 := float32(math.Float32frombits(v))
			m.Noise = &v2
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pos", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEic
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pos = append(m.Pos, &ObservedPos{})
			if err := m.Pos[len(m.Pos)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowEic
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Source = append(m.Source, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowEic
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthEic
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowEic
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Source = append(m.Source, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEic(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEic
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Track) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEic
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Track: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Track: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Segment", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEic
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Segment = append(m.Segment, &TrackSegment{})
			if err := m.Segment[len(m.Segment)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowEic
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Observation = append(m.Observation, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowEic
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthEic
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowEic
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Observation = append(m.Observation, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Observation", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEic(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEic
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TrackSegment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEic
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TrackSegment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TrackSegment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vertex", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEic
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Vertex == nil {
				m.Vertex = &XYZTD{}
			}
			if err := m.Vertex.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vertexnoise", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEic
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Vertexnoise = append(m.Vertexnoise, &RandVar{})
			if err := m.Vertexnoise[len(m.Vertexnoise)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Poq", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEic
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Poq == nil {
				m.Poq = &XYZD{}
			}
			if err := m.Poq.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Poqnoise", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEic
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Poqnoise = append(m.Poqnoise, &RandVar{})
			if err := m.Poqnoise[len(m.Poqnoise)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Curvature", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEic
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Curvature == nil {
				m.Curvature = &XYZD{}
			}
			if err := m.Curvature.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Curvaturenoise", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEic
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Curvaturenoise = append(m.Curvaturenoise, &RandVar{})
			if err := m.Curvaturenoise[len(m.Curvaturenoise)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chargesign", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			v2 := float32(math.Float32frombits(v))
			m.Chargesign = &v2
		case 8:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Length", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			v2 := float32(math.Float32frombits(v))
			m.Length = &v2
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Magfield", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEic
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Magfield == nil {
				m.Magfield = &XYZD{}
			}
			if err := m.Magfield.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEic(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEic
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ObservedPos) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEic
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ObservedPos: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ObservedPos: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mean", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEic
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Mean == nil {
				m.Mean = &XYZTD{}
			}
			if err := m.Mean.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Noise", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEic
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Noise = append(m.Noise, &RandVar{})
			if err := m.Noise[len(m.Noise)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Weightmod", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			v2 := float32(math.Float32frombits(v))
			m.Weightmod = &v2
		default:
			iNdEx = preIndex
			skippy, err := skipEic(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEic
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RandVar) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEic
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RandVar: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RandVar: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dist", wireType)
			}
			var v RandVar_Distribution
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (RandVar_Distribution(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Dist = &v
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sigma", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEic
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Sigma == nil {
				m.Sigma = &XYZTF{}
			}
			if err := m.Sigma.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEic(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEic
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *XYZTD) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEic
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: XYZTD: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: XYZTD: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field X", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			v2 := float64(math.Float64frombits(v))
			m.X = &v2
		case 2:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Y", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			v2 := float64(math.Float64frombits(v))
			m.Y = &v2
		case 3:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Z", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			v2 := float64(math.Float64frombits(v))
			m.Z = &v2
		case 4:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field T", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			v2 := float64(math.Float64frombits(v))
			m.T = &v2
		default:
			iNdEx = preIndex
			skippy, err := skipEic(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEic
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *XYZTF) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEic
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: XYZTF: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: XYZTF: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field X", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			v2 := float32(math.Float32frombits(v))
			m.X = &v2
		case 2:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Y", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			v2 := float32(math.Float32frombits(v))
			m.Y = &v2
		case 3:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Z", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			v2 := float32(math.Float32frombits(v))
			m.Z = &v2
		case 4:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field T", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			v2 := float32(math.Float32frombits(v))
			m.T = &v2
		default:
			iNdEx = preIndex
			skippy, err := skipEic(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEic
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *XYZD) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEic
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: XYZD: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: XYZD: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field X", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			v2 := float64(math.Float64frombits(v))
			m.X = &v2
		case 2:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Y", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			v2 := float64(math.Float64frombits(v))
			m.Y = &v2
		case 3:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Z", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			v2 := float64(math.Float64frombits(v))
			m.Z = &v2
		default:
			iNdEx = preIndex
			skippy, err := skipEic(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEic
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *XYZF) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEic
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: XYZF: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: XYZF: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field X", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			v2 := float32(math.Float32frombits(v))
			m.X = &v2
		case 2:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Y", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			v2 := float32(math.Float32frombits(v))
			m.Y = &v2
		case 3:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Z", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			v2 := float32(math.Float32frombits(v))
			m.Z = &v2
		default:
			iNdEx = preIndex
			skippy, err := skipEic(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEic
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEic(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEic
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEic
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEic
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthEic
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowEic
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipEic(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthEic = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEic   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("proio/model/eic.proto", fileDescriptor_eic_b0c1cfa6a8a64341) }

var fileDescriptor_eic_b0c1cfa6a8a64341 = []byte{
	// 803 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xdb, 0x6e, 0xdb, 0x46,
	0x10, 0xf5, 0x92, 0xd4, 0x6d, 0xa8, 0xba, 0xee, 0xa2, 0x36, 0x88, 0xc2, 0x55, 0x05, 0x16, 0x85,
	0xd5, 0xa2, 0xa5, 0x6c, 0xb5, 0x40, 0x51, 0xa3, 0x40, 0x12, 0x43, 0x16, 0x12, 0x20, 0xbe, 0x60,
	0x6d, 0x07, 0x89, 0x5f, 0x02, 0x8a, 0xdc, 0x50, 0x8b, 0x90, 0x5c, 0x9a, 0xa4, 0x1c, 0xdb, 0x40,
	0x9e, 0xf3, 0x0b, 0x01, 0xf2, 0x29, 0xf9, 0x81, 0xe4, 0x25, 0xc8, 0x27, 0x04, 0xce, 0x8f, 0x04,
	0xbb, 0xa4, 0x24, 0xca, 0x8e, 0x64, 0xe7, 0x8d, 0x67, 0x70, 0x66, 0xce, 0xcc, 0xce, 0x19, 0x09,
	0x96, 0xa3, 0x98, 0x33, 0xde, 0x0e, 0xb8, 0x4b, 0xfd, 0x36, 0x65, 0x8e, 0x15, 0xc5, 0x3c, 0xe5,
	0xf8, 0x7b, 0x19, 0xb6, 0x64, 0xd8, 0xa2, 0xcc, 0x31, 0xdf, 0x2b, 0x50, 0xdd, 0xb7, 0xe3, 0x94,
	0x39, 0x3e, 0xc5, 0x2b, 0x50, 0x8e, 0xec, 0x98, 0x86, 0xa9, 0x81, 0x9a, 0x6a, 0x4b, 0x23, 0x39,
	0xc2, 0x3f, 0x42, 0xc9, 0x19, 0x30, 0xdf, 0x35, 0x14, 0x19, 0xce, 0x00, 0x5e, 0x02, 0x35, 0x72,
	0x3d, 0x43, 0x6d, 0xa2, 0xd6, 0x0f, 0x44, 0x7c, 0x62, 0x0b, 0xca, 0xa7, 0x34, 0x4e, 0xe9, 0x99,
	0xa1, 0x35, 0x51, 0x4b, 0xef, 0xac, 0x58, 0x57, 0xe4, 0xac, 0xc7, 0x4f, 0x8e, 0x0f, 0xbb, 0x24,
	0x67, 0xe1, 0x75, 0xa8, 0x46, 0x4f, 0x5d, 0x3e, 0xec, 0xfb, 0xd4, 0x28, 0xc9, 0x8c, 0xe5, 0xaf,
	0x65, 0x74, 0x49, 0x25, 0xea, 0x4a, 0x16, 0xfe, 0x05, 0xf4, 0xc0, 0x4e, 0x92, 0x51, 0x52, 0xb9,
	0x89, 0x5a, 0x88, 0x80, 0x08, 0xe5, 0x84, 0x15, 0x28, 0x3b, 0x03, 0x3b, 0xf6, 0xa8, 0x51, 0x69,
	0xa2, 0x96, 0x42, 0x72, 0x84, 0x7f, 0x07, 0x2d, 0x89, 0x58, 0x68, 0x54, 0x67, 0xcb, 0xf4, 0x88,
	0xa4, 0xe0, 0x5f, 0x01, 0x45, 0x46, 0x6d, 0x1e, 0x0f, 0x45, 0x18, 0x83, 0x26, 0x54, 0x0d, 0x90,
	0x2a, 0xf2, 0xdb, 0xfc, 0x80, 0xa0, 0x7c, 0xc0, 0x82, 0xfb, 0x2c, 0xc5, 0x3f, 0x41, 0xf5, 0x94,
	0xfb, 0xc3, 0x80, 0x32, 0xd7, 0x40, 0x4d, 0xd4, 0xd2, 0xc8, 0x18, 0xe3, 0x4d, 0xa8, 0x7b, 0x3e,
	0xef, 0xdb, 0x7e, 0x14, 0xd3, 0x88, 0x27, 0x86, 0x32, 0xf7, 0xad, 0xa6, 0xb8, 0xf8, 0x7f, 0xf8,
	0x2e, 0xc7, 0x3c, 0x49, 0x45, 0xb2, 0x3a, 0x37, 0x79, 0x9a, 0x2c, 0x9a, 0xa6, 0x2e, 0x8d, 0xe4,
	0x76, 0x14, 0x22, 0xbf, 0x45, 0xa7, 0x51, 0xbe, 0x7f, 0xb9, 0x03, 0x8d, 0x8c, 0xb1, 0xf9, 0x12,
	0x6a, 0xdb, 0x21, 0x8d, 0xbd, 0xf3, 0x2e, 0xcd, 0x26, 0xa6, 0x76, 0x28, 0xc7, 0x11, 0x13, 0x53,
	0x3b, 0x14, 0xc6, 0x08, 0x39, 0x4b, 0xa8, 0x9c, 0x41, 0x21, 0x19, 0xc0, 0x16, 0xa8, 0x59, 0x6b,
	0x6a, 0x4b, 0xef, 0xac, 0x5e, 0x6b, 0x6d, 0xaf, 0x9f, 0xd0, 0xf8, 0x94, 0xba, 0xfb, 0x3c, 0x21,
	0x82, 0x28, 0x76, 0x96, 0xf0, 0x61, 0xec, 0x50, 0x43, 0xcb, 0x6c, 0x97, 0x21, 0xb3, 0x0f, 0xa5,
	0xc3, 0xd8, 0x76, 0x9e, 0xe3, 0x7f, 0xa1, 0x92, 0x50, 0x2f, 0x18, 0x19, 0x53, 0xef, 0xfc, 0x7c,
	0xad, 0xa8, 0x24, 0x1e, 0x64, 0x24, 0x32, 0x62, 0xe3, 0x26, 0xe8, 0x5c, 0xaa, 0xd9, 0x29, 0xe3,
	0x61, 0x6e, 0xdf, 0x62, 0xc8, 0x7c, 0xab, 0x42, 0xbd, 0x98, 0x5b, 0xf0, 0x30, 0xba, 0x95, 0x87,
	0x37, 0x41, 0xcf, 0xbe, 0x46, 0x0f, 0x21, 0xfa, 0x33, 0xae, 0x25, 0x11, 0x3b, 0x74, 0x1f, 0xd9,
	0x31, 0x29, 0x92, 0xf1, 0x9a, 0x78, 0xa8, 0x93, 0x7c, 0x87, 0x33, 0xac, 0x2f, 0x18, 0xf8, 0x1f,
	0xa8, 0x46, 0xfc, 0x24, 0x53, 0xd0, 0x6e, 0x50, 0x18, 0x33, 0xf1, 0xdf, 0x50, 0x73, 0x86, 0x62,
	0xd0, 0x61, 0x7c, 0xc3, 0x7d, 0x4d, 0x78, 0xf8, 0x2e, 0x2c, 0x8e, 0x41, 0x26, 0x58, 0xbe, 0x41,
	0xf0, 0x0a, 0x1f, 0x37, 0x00, 0xb2, 0xa3, 0x4b, 0x98, 0x17, 0xe6, 0x67, 0x58, 0x88, 0x88, 0x75,
	0xfb, 0x34, 0xf4, 0xd2, 0x81, 0x3c, 0x46, 0x85, 0xe4, 0x08, 0x6f, 0x40, 0x35, 0xb0, 0xbd, 0x67,
	0x8c, 0xfa, 0xee, 0xbc, 0xf3, 0xeb, 0x92, 0x31, 0xcd, 0x7c, 0x85, 0x40, 0x2f, 0xd8, 0x09, 0xff,
	0x51, 0xf0, 0xe8, 0xec, 0xd5, 0x65, 0xde, 0xb5, 0x26, 0xde, 0x9d, 0x3f, 0x5f, 0xee, 0xea, 0x55,
	0xa8, 0xbd, 0xa0, 0xcc, 0x1b, 0xa4, 0x01, 0x77, 0xe5, 0xca, 0x14, 0x32, 0x09, 0x98, 0x6f, 0x10,
	0x54, 0xf2, 0x04, 0xfc, 0x1f, 0x68, 0x2e, 0x4b, 0x52, 0x79, 0x14, 0x8b, 0x9d, 0xdf, 0x66, 0x15,
	0xb6, 0xba, 0x2c, 0x49, 0x63, 0xd6, 0x1f, 0x0a, 0x23, 0x12, 0x99, 0x82, 0xff, 0x84, 0x52, 0xc2,
	0xbc, 0xc0, 0x9e, 0x7b, 0xd7, 0x3d, 0x92, 0x91, 0xcc, 0x35, 0xa8, 0x17, 0x6b, 0x60, 0x80, 0xf2,
	0xee, 0x1e, 0xd9, 0xb9, 0xf7, 0x70, 0x69, 0x01, 0xeb, 0x50, 0x39, 0xda, 0x7d, 0xd0, 0xdb, 0x23,
	0x3b, 0x4b, 0xc8, 0xbc, 0x03, 0x25, 0x39, 0x3a, 0xae, 0x03, 0xca, 0x8c, 0x8d, 0x08, 0x3a, 0x13,
	0xe8, 0x5c, 0x76, 0x89, 0x08, 0x3a, 0x17, 0xe8, 0x42, 0xea, 0x22, 0x82, 0x2e, 0x04, 0x4a, 0xe5,
	0x0f, 0x05, 0x22, 0x28, 0x1d, 0x15, 0xe8, 0x4d, 0x0a, 0x28, 0x53, 0x05, 0x94, 0xa9, 0x02, 0xca,
	0x54, 0x01, 0x45, 0x14, 0x58, 0x07, 0x4d, 0xec, 0xee, 0xf6, 0x0d, 0xe4, 0x19, 0xdf, 0xa0, 0xb8,
	0x75, 0xf4, 0xee, 0xb2, 0x81, 0x3e, 0x5e, 0x36, 0xd0, 0xa7, 0xcb, 0x06, 0x7a, 0xfd, 0xb9, 0xb1,
	0x00, 0x7a, 0xe1, 0xf9, 0xb6, 0xd4, 0x6d, 0xe6, 0x1c, 0x6f, 0x78, 0x2c, 0x1d, 0x0c, 0xfb, 0x96,
	0xc3, 0x83, 0xb6, 0x4b, 0x1d, 0xd6, 0xa7, 0xbe, 0xc3, 0x79, 0x44, 0xe3, 0x76, 0xf6, 0x87, 0xe9,
	0xf1, 0xbf, 0xae, 0xfc, 0x73, 0x7e, 0x09, 0x00, 0x00, 0xff, 0xff, 0x10, 0xc5, 0xed, 0xcf, 0x4b,
	0x07, 0x00, 0x00,
}
