// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eicio.proto

/*
Package eicio is a generated protocol buffer package.

It is generated from these files:
	eicio.proto

It has these top-level messages:
	EventHeader
	Params
	MCParticle
	MCParticleCollection
	SimTrackerHit
	SimTrackerHitCollection
	TrackerData
	TrackerDataCollection
	TrackerRawData
	TrackerRawDataCollection
	TrackerHit
	TrackerHitCollection
	TrackerPulse
	TrackerPulseCollection
	TrackerHitPlane
	TrackerHitPlaneCollection
	TrackerHitZCylinder
	TrackerHitZCylinderCollection
	Track
	TrackCollection
	Contrib
	SimCalorimeterHit
	SimCalorimeterHitCollection
	RawCalorimeterHit
	RawCalorimeterHitCollection
	CalorimeterHit
	CalorimeterHitCollection
	Cluster
	ClusterCollection
	RecParticle
	RecParticleCollection
*/
package eicio

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EventHeader_CollectionHeader_Type int32

const (
	EventHeader_CollectionHeader_NONE                EventHeader_CollectionHeader_Type = 0
	EventHeader_CollectionHeader_MCParticle          EventHeader_CollectionHeader_Type = 1
	EventHeader_CollectionHeader_SimTrackerHit       EventHeader_CollectionHeader_Type = 2
	EventHeader_CollectionHeader_TrackerData         EventHeader_CollectionHeader_Type = 3
	EventHeader_CollectionHeader_TrackerRawData      EventHeader_CollectionHeader_Type = 4
	EventHeader_CollectionHeader_TrackerHit          EventHeader_CollectionHeader_Type = 5
	EventHeader_CollectionHeader_TrackerPulse        EventHeader_CollectionHeader_Type = 6
	EventHeader_CollectionHeader_TrackerHitPlane     EventHeader_CollectionHeader_Type = 7
	EventHeader_CollectionHeader_TrackerHitZCylinder EventHeader_CollectionHeader_Type = 8
	EventHeader_CollectionHeader_Track               EventHeader_CollectionHeader_Type = 9
	EventHeader_CollectionHeader_SimCalorimeterHit   EventHeader_CollectionHeader_Type = 10
	EventHeader_CollectionHeader_RawCalorimeterHit   EventHeader_CollectionHeader_Type = 11
	EventHeader_CollectionHeader_CalorimeterHit      EventHeader_CollectionHeader_Type = 12
	EventHeader_CollectionHeader_Cluster             EventHeader_CollectionHeader_Type = 13
	EventHeader_CollectionHeader_RecParticle         EventHeader_CollectionHeader_Type = 14
	EventHeader_CollectionHeader_Vertex              EventHeader_CollectionHeader_Type = 15
	EventHeader_CollectionHeader_Relation            EventHeader_CollectionHeader_Type = 16
)

var EventHeader_CollectionHeader_Type_name = map[int32]string{
	0:  "NONE",
	1:  "MCParticle",
	2:  "SimTrackerHit",
	3:  "TrackerData",
	4:  "TrackerRawData",
	5:  "TrackerHit",
	6:  "TrackerPulse",
	7:  "TrackerHitPlane",
	8:  "TrackerHitZCylinder",
	9:  "Track",
	10: "SimCalorimeterHit",
	11: "RawCalorimeterHit",
	12: "CalorimeterHit",
	13: "Cluster",
	14: "RecParticle",
	15: "Vertex",
	16: "Relation",
}
var EventHeader_CollectionHeader_Type_value = map[string]int32{
	"NONE":                0,
	"MCParticle":          1,
	"SimTrackerHit":       2,
	"TrackerData":         3,
	"TrackerRawData":      4,
	"TrackerHit":          5,
	"TrackerPulse":        6,
	"TrackerHitPlane":     7,
	"TrackerHitZCylinder": 8,
	"Track":               9,
	"SimCalorimeterHit":   10,
	"RawCalorimeterHit":   11,
	"CalorimeterHit":      12,
	"Cluster":             13,
	"RecParticle":         14,
	"Vertex":              15,
	"Relation":            16,
}

func (x EventHeader_CollectionHeader_Type) String() string {
	return proto.EnumName(EventHeader_CollectionHeader_Type_name, int32(x))
}
func (EventHeader_CollectionHeader_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0, 0}
}

type MCParticle_GenStatus int32

const (
	MCParticle_FINALSTATE    MCParticle_GenStatus = 0
	MCParticle_DOCUMENTATION MCParticle_GenStatus = 1
)

var MCParticle_GenStatus_name = map[int32]string{
	0: "FINALSTATE",
	1: "DOCUMENTATION",
}
var MCParticle_GenStatus_value = map[string]int32{
	"FINALSTATE":    0,
	"DOCUMENTATION": 1,
}

func (x MCParticle_GenStatus) String() string {
	return proto.EnumName(MCParticle_GenStatus_name, int32(x))
}
func (MCParticle_GenStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type EventHeader struct {
	Id          uint64                          `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	VMajor      uint32                          `protobuf:"varint,2,opt,name=vMajor" json:"vMajor,omitempty"`
	VMinor      uint32                          `protobuf:"varint,3,opt,name=vMinor" json:"vMinor,omitempty"`
	Collection  []*EventHeader_CollectionHeader `protobuf:"bytes,4,rep,name=collection" json:"collection,omitempty"`
	Description string                          `protobuf:"bytes,16,opt,name=description" json:"description,omitempty"`
}

func (m *EventHeader) Reset()                    { *m = EventHeader{} }
func (m *EventHeader) String() string            { return proto.CompactTextString(m) }
func (*EventHeader) ProtoMessage()               {}
func (*EventHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EventHeader) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EventHeader) GetVMajor() uint32 {
	if m != nil {
		return m.VMajor
	}
	return 0
}

func (m *EventHeader) GetVMinor() uint32 {
	if m != nil {
		return m.VMinor
	}
	return 0
}

func (m *EventHeader) GetCollection() []*EventHeader_CollectionHeader {
	if m != nil {
		return m.Collection
	}
	return nil
}

func (m *EventHeader) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type EventHeader_CollectionHeader struct {
	Type        EventHeader_CollectionHeader_Type `protobuf:"varint,1,opt,name=type,enum=eicio.EventHeader_CollectionHeader_Type" json:"type,omitempty"`
	Name        string                            `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	PayloadSize uint32                            `protobuf:"varint,3,opt,name=payloadSize" json:"payloadSize,omitempty"`
}

func (m *EventHeader_CollectionHeader) Reset()                    { *m = EventHeader_CollectionHeader{} }
func (m *EventHeader_CollectionHeader) String() string            { return proto.CompactTextString(m) }
func (*EventHeader_CollectionHeader) ProtoMessage()               {}
func (*EventHeader_CollectionHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *EventHeader_CollectionHeader) GetType() EventHeader_CollectionHeader_Type {
	if m != nil {
		return m.Type
	}
	return EventHeader_CollectionHeader_NONE
}

func (m *EventHeader_CollectionHeader) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EventHeader_CollectionHeader) GetPayloadSize() uint32 {
	if m != nil {
		return m.PayloadSize
	}
	return 0
}

type Params struct {
	Ints    map[string]int32   `protobuf:"bytes,1,rep,name=ints" json:"ints,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Floats  map[string]float32 `protobuf:"bytes,2,rep,name=floats" json:"floats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	Strings map[string]string  `protobuf:"bytes,3,rep,name=strings" json:"strings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Params) Reset()                    { *m = Params{} }
func (m *Params) String() string            { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()               {}
func (*Params) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Params) GetInts() map[string]int32 {
	if m != nil {
		return m.Ints
	}
	return nil
}

func (m *Params) GetFloats() map[string]float32 {
	if m != nil {
		return m.Floats
	}
	return nil
}

func (m *Params) GetStrings() map[string]string {
	if m != nil {
		return m.Strings
	}
	return nil
}

type MCParticle struct {
	Parents   []int32              `protobuf:"varint,1,rep,packed,name=parents" json:"parents,omitempty"`
	Children  []int32              `protobuf:"varint,2,rep,packed,name=children" json:"children,omitempty"`
	PDG       int32                `protobuf:"varint,3,opt,name=PDG" json:"PDG,omitempty"`
	Vertex    []float64            `protobuf:"fixed64,4,rep,packed,name=vertex" json:"vertex,omitempty"`
	Time      float32              `protobuf:"fixed32,5,opt,name=time" json:"time,omitempty"`
	P         []float64            `protobuf:"fixed64,6,rep,packed,name=p" json:"p,omitempty"`
	Mass      float64              `protobuf:"fixed64,7,opt,name=mass" json:"mass,omitempty"`
	Charge    float32              `protobuf:"fixed32,8,opt,name=charge" json:"charge,omitempty"`
	PEndPoint []float64            `protobuf:"fixed64,9,rep,packed,name=PEndPoint" json:"PEndPoint,omitempty"`
	Spin      []float32            `protobuf:"fixed32,10,rep,packed,name=spin" json:"spin,omitempty"`
	ColorFlow []int32              `protobuf:"varint,11,rep,packed,name=colorFlow" json:"colorFlow,omitempty"`
	GenStatus MCParticle_GenStatus `protobuf:"varint,12,opt,name=genStatus,enum=eicio.MCParticle_GenStatus" json:"genStatus,omitempty"`
	SimStatus uint32               `protobuf:"varint,13,opt,name=simStatus" json:"simStatus,omitempty"`
}

func (m *MCParticle) Reset()                    { *m = MCParticle{} }
func (m *MCParticle) String() string            { return proto.CompactTextString(m) }
func (*MCParticle) ProtoMessage()               {}
func (*MCParticle) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MCParticle) GetParents() []int32 {
	if m != nil {
		return m.Parents
	}
	return nil
}

func (m *MCParticle) GetChildren() []int32 {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *MCParticle) GetPDG() int32 {
	if m != nil {
		return m.PDG
	}
	return 0
}

func (m *MCParticle) GetVertex() []float64 {
	if m != nil {
		return m.Vertex
	}
	return nil
}

func (m *MCParticle) GetTime() float32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *MCParticle) GetP() []float64 {
	if m != nil {
		return m.P
	}
	return nil
}

func (m *MCParticle) GetMass() float64 {
	if m != nil {
		return m.Mass
	}
	return 0
}

func (m *MCParticle) GetCharge() float32 {
	if m != nil {
		return m.Charge
	}
	return 0
}

func (m *MCParticle) GetPEndPoint() []float64 {
	if m != nil {
		return m.PEndPoint
	}
	return nil
}

func (m *MCParticle) GetSpin() []float32 {
	if m != nil {
		return m.Spin
	}
	return nil
}

func (m *MCParticle) GetColorFlow() []int32 {
	if m != nil {
		return m.ColorFlow
	}
	return nil
}

func (m *MCParticle) GetGenStatus() MCParticle_GenStatus {
	if m != nil {
		return m.GenStatus
	}
	return MCParticle_FINALSTATE
}

func (m *MCParticle) GetSimStatus() uint32 {
	if m != nil {
		return m.SimStatus
	}
	return 0
}

type MCParticleCollection struct {
	Particle []*MCParticle `protobuf:"bytes,1,rep,name=particle" json:"particle,omitempty"`
}

func (m *MCParticleCollection) Reset()                    { *m = MCParticleCollection{} }
func (m *MCParticleCollection) String() string            { return proto.CompactTextString(m) }
func (*MCParticleCollection) ProtoMessage()               {}
func (*MCParticleCollection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MCParticleCollection) GetParticle() []*MCParticle {
	if m != nil {
		return m.Particle
	}
	return nil
}

type SimTrackerHit struct {
	CellID0    int32     `protobuf:"varint,1,opt,name=cellID0" json:"cellID0,omitempty"`
	CellID1    int32     `protobuf:"varint,2,opt,name=cellID1" json:"cellID1,omitempty"`
	Pos        []float64 `protobuf:"fixed64,3,rep,packed,name=pos" json:"pos,omitempty"`
	EDep       float32   `protobuf:"fixed32,4,opt,name=EDep" json:"EDep,omitempty"`
	Time       float32   `protobuf:"fixed32,5,opt,name=time" json:"time,omitempty"`
	Mc         uint32    `protobuf:"varint,6,opt,name=mc" json:"mc,omitempty"`
	P          float32   `protobuf:"fixed32,7,opt,name=p" json:"p,omitempty"`
	PathLength float32   `protobuf:"fixed32,8,opt,name=pathLength" json:"pathLength,omitempty"`
	Quality    int32     `protobuf:"varint,9,opt,name=quality" json:"quality,omitempty"`
}

func (m *SimTrackerHit) Reset()                    { *m = SimTrackerHit{} }
func (m *SimTrackerHit) String() string            { return proto.CompactTextString(m) }
func (*SimTrackerHit) ProtoMessage()               {}
func (*SimTrackerHit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SimTrackerHit) GetCellID0() int32 {
	if m != nil {
		return m.CellID0
	}
	return 0
}

func (m *SimTrackerHit) GetCellID1() int32 {
	if m != nil {
		return m.CellID1
	}
	return 0
}

func (m *SimTrackerHit) GetPos() []float64 {
	if m != nil {
		return m.Pos
	}
	return nil
}

func (m *SimTrackerHit) GetEDep() float32 {
	if m != nil {
		return m.EDep
	}
	return 0
}

func (m *SimTrackerHit) GetTime() float32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *SimTrackerHit) GetMc() uint32 {
	if m != nil {
		return m.Mc
	}
	return 0
}

func (m *SimTrackerHit) GetP() float32 {
	if m != nil {
		return m.P
	}
	return 0
}

func (m *SimTrackerHit) GetPathLength() float32 {
	if m != nil {
		return m.PathLength
	}
	return 0
}

func (m *SimTrackerHit) GetQuality() int32 {
	if m != nil {
		return m.Quality
	}
	return 0
}

type SimTrackerHitCollection struct {
	Hit []*SimTrackerHit `protobuf:"bytes,1,rep,name=hit" json:"hit,omitempty"`
}

func (m *SimTrackerHitCollection) Reset()                    { *m = SimTrackerHitCollection{} }
func (m *SimTrackerHitCollection) String() string            { return proto.CompactTextString(m) }
func (*SimTrackerHitCollection) ProtoMessage()               {}
func (*SimTrackerHitCollection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SimTrackerHitCollection) GetHit() []*SimTrackerHit {
	if m != nil {
		return m.Hit
	}
	return nil
}

type TrackerData struct {
}

func (m *TrackerData) Reset()                    { *m = TrackerData{} }
func (m *TrackerData) String() string            { return proto.CompactTextString(m) }
func (*TrackerData) ProtoMessage()               {}
func (*TrackerData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type TrackerDataCollection struct {
	Data []*TrackerData `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
}

func (m *TrackerDataCollection) Reset()                    { *m = TrackerDataCollection{} }
func (m *TrackerDataCollection) String() string            { return proto.CompactTextString(m) }
func (*TrackerDataCollection) ProtoMessage()               {}
func (*TrackerDataCollection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *TrackerDataCollection) GetData() []*TrackerData {
	if m != nil {
		return m.Data
	}
	return nil
}

type TrackerRawData struct {
}

func (m *TrackerRawData) Reset()                    { *m = TrackerRawData{} }
func (m *TrackerRawData) String() string            { return proto.CompactTextString(m) }
func (*TrackerRawData) ProtoMessage()               {}
func (*TrackerRawData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type TrackerRawDataCollection struct {
	Data []*TrackerRawData `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
}

func (m *TrackerRawDataCollection) Reset()                    { *m = TrackerRawDataCollection{} }
func (m *TrackerRawDataCollection) String() string            { return proto.CompactTextString(m) }
func (*TrackerRawDataCollection) ProtoMessage()               {}
func (*TrackerRawDataCollection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *TrackerRawDataCollection) GetData() []*TrackerRawData {
	if m != nil {
		return m.Data
	}
	return nil
}

type TrackerHit struct {
}

func (m *TrackerHit) Reset()                    { *m = TrackerHit{} }
func (m *TrackerHit) String() string            { return proto.CompactTextString(m) }
func (*TrackerHit) ProtoMessage()               {}
func (*TrackerHit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type TrackerHitCollection struct {
	Hit []*TrackerHit `protobuf:"bytes,1,rep,name=hit" json:"hit,omitempty"`
}

func (m *TrackerHitCollection) Reset()                    { *m = TrackerHitCollection{} }
func (m *TrackerHitCollection) String() string            { return proto.CompactTextString(m) }
func (*TrackerHitCollection) ProtoMessage()               {}
func (*TrackerHitCollection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *TrackerHitCollection) GetHit() []*TrackerHit {
	if m != nil {
		return m.Hit
	}
	return nil
}

type TrackerPulse struct {
}

func (m *TrackerPulse) Reset()                    { *m = TrackerPulse{} }
func (m *TrackerPulse) String() string            { return proto.CompactTextString(m) }
func (*TrackerPulse) ProtoMessage()               {}
func (*TrackerPulse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type TrackerPulseCollection struct {
	Pulse []*TrackerPulse `protobuf:"bytes,1,rep,name=pulse" json:"pulse,omitempty"`
}

func (m *TrackerPulseCollection) Reset()                    { *m = TrackerPulseCollection{} }
func (m *TrackerPulseCollection) String() string            { return proto.CompactTextString(m) }
func (*TrackerPulseCollection) ProtoMessage()               {}
func (*TrackerPulseCollection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *TrackerPulseCollection) GetPulse() []*TrackerPulse {
	if m != nil {
		return m.Pulse
	}
	return nil
}

type TrackerHitPlane struct {
}

func (m *TrackerHitPlane) Reset()                    { *m = TrackerHitPlane{} }
func (m *TrackerHitPlane) String() string            { return proto.CompactTextString(m) }
func (*TrackerHitPlane) ProtoMessage()               {}
func (*TrackerHitPlane) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type TrackerHitPlaneCollection struct {
	Plane []*TrackerHitPlane `protobuf:"bytes,1,rep,name=plane" json:"plane,omitempty"`
}

func (m *TrackerHitPlaneCollection) Reset()                    { *m = TrackerHitPlaneCollection{} }
func (m *TrackerHitPlaneCollection) String() string            { return proto.CompactTextString(m) }
func (*TrackerHitPlaneCollection) ProtoMessage()               {}
func (*TrackerHitPlaneCollection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *TrackerHitPlaneCollection) GetPlane() []*TrackerHitPlane {
	if m != nil {
		return m.Plane
	}
	return nil
}

type TrackerHitZCylinder struct {
}

func (m *TrackerHitZCylinder) Reset()                    { *m = TrackerHitZCylinder{} }
func (m *TrackerHitZCylinder) String() string            { return proto.CompactTextString(m) }
func (*TrackerHitZCylinder) ProtoMessage()               {}
func (*TrackerHitZCylinder) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

type TrackerHitZCylinderCollection struct {
	Cyl []*TrackerHitZCylinder `protobuf:"bytes,1,rep,name=cyl" json:"cyl,omitempty"`
}

func (m *TrackerHitZCylinderCollection) Reset()                    { *m = TrackerHitZCylinderCollection{} }
func (m *TrackerHitZCylinderCollection) String() string            { return proto.CompactTextString(m) }
func (*TrackerHitZCylinderCollection) ProtoMessage()               {}
func (*TrackerHitZCylinderCollection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *TrackerHitZCylinderCollection) GetCyl() []*TrackerHitZCylinder {
	if m != nil {
		return m.Cyl
	}
	return nil
}

type Track struct {
}

func (m *Track) Reset()                    { *m = Track{} }
func (m *Track) String() string            { return proto.CompactTextString(m) }
func (*Track) ProtoMessage()               {}
func (*Track) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

type TrackCollection struct {
	Track []*Track `protobuf:"bytes,1,rep,name=track" json:"track,omitempty"`
}

func (m *TrackCollection) Reset()                    { *m = TrackCollection{} }
func (m *TrackCollection) String() string            { return proto.CompactTextString(m) }
func (*TrackCollection) ProtoMessage()               {}
func (*TrackCollection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *TrackCollection) GetTrack() []*Track {
	if m != nil {
		return m.Track
	}
	return nil
}

type Contrib struct {
	MCParticle int32     `protobuf:"varint,1,opt,name=MCParticle" json:"MCParticle,omitempty"`
	Energy     float32   `protobuf:"fixed32,2,opt,name=energy" json:"energy,omitempty"`
	Time       float32   `protobuf:"fixed32,3,opt,name=time" json:"time,omitempty"`
	PDG        int32     `protobuf:"varint,4,opt,name=PDG" json:"PDG,omitempty"`
	StepPos    []float32 `protobuf:"fixed32,5,rep,packed,name=stepPos" json:"stepPos,omitempty"`
}

func (m *Contrib) Reset()                    { *m = Contrib{} }
func (m *Contrib) String() string            { return proto.CompactTextString(m) }
func (*Contrib) ProtoMessage()               {}
func (*Contrib) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *Contrib) GetMCParticle() int32 {
	if m != nil {
		return m.MCParticle
	}
	return 0
}

func (m *Contrib) GetEnergy() float32 {
	if m != nil {
		return m.Energy
	}
	return 0
}

func (m *Contrib) GetTime() float32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Contrib) GetPDG() int32 {
	if m != nil {
		return m.PDG
	}
	return 0
}

func (m *Contrib) GetStepPos() []float32 {
	if m != nil {
		return m.StepPos
	}
	return nil
}

type SimCalorimeterHit struct {
	Params        *Params   `protobuf:"bytes,1,opt,name=params" json:"params,omitempty"`
	CellID0       int32     `protobuf:"varint,2,opt,name=cellID0" json:"cellID0,omitempty"`
	CellID1       int32     `protobuf:"varint,3,opt,name=cellID1" json:"cellID1,omitempty"`
	Energy        float32   `protobuf:"fixed32,4,opt,name=energy" json:"energy,omitempty"`
	Pos           []float32 `protobuf:"fixed32,5,rep,packed,name=pos" json:"pos,omitempty"`
	Contributions *Contrib  `protobuf:"bytes,6,opt,name=contributions" json:"contributions,omitempty"`
}

func (m *SimCalorimeterHit) Reset()                    { *m = SimCalorimeterHit{} }
func (m *SimCalorimeterHit) String() string            { return proto.CompactTextString(m) }
func (*SimCalorimeterHit) ProtoMessage()               {}
func (*SimCalorimeterHit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *SimCalorimeterHit) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *SimCalorimeterHit) GetCellID0() int32 {
	if m != nil {
		return m.CellID0
	}
	return 0
}

func (m *SimCalorimeterHit) GetCellID1() int32 {
	if m != nil {
		return m.CellID1
	}
	return 0
}

func (m *SimCalorimeterHit) GetEnergy() float32 {
	if m != nil {
		return m.Energy
	}
	return 0
}

func (m *SimCalorimeterHit) GetPos() []float32 {
	if m != nil {
		return m.Pos
	}
	return nil
}

func (m *SimCalorimeterHit) GetContributions() *Contrib {
	if m != nil {
		return m.Contributions
	}
	return nil
}

type SimCalorimeterHitCollection struct {
	Hit []*SimCalorimeterHit `protobuf:"bytes,1,rep,name=hit" json:"hit,omitempty"`
}

func (m *SimCalorimeterHitCollection) Reset()                    { *m = SimCalorimeterHitCollection{} }
func (m *SimCalorimeterHitCollection) String() string            { return proto.CompactTextString(m) }
func (*SimCalorimeterHitCollection) ProtoMessage()               {}
func (*SimCalorimeterHitCollection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *SimCalorimeterHitCollection) GetHit() []*SimCalorimeterHit {
	if m != nil {
		return m.Hit
	}
	return nil
}

type RawCalorimeterHit struct {
}

func (m *RawCalorimeterHit) Reset()                    { *m = RawCalorimeterHit{} }
func (m *RawCalorimeterHit) String() string            { return proto.CompactTextString(m) }
func (*RawCalorimeterHit) ProtoMessage()               {}
func (*RawCalorimeterHit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

type RawCalorimeterHitCollection struct {
	Hit []*RawCalorimeterHit `protobuf:"bytes,1,rep,name=hit" json:"hit,omitempty"`
}

func (m *RawCalorimeterHitCollection) Reset()                    { *m = RawCalorimeterHitCollection{} }
func (m *RawCalorimeterHitCollection) String() string            { return proto.CompactTextString(m) }
func (*RawCalorimeterHitCollection) ProtoMessage()               {}
func (*RawCalorimeterHitCollection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *RawCalorimeterHitCollection) GetHit() []*RawCalorimeterHit {
	if m != nil {
		return m.Hit
	}
	return nil
}

type CalorimeterHit struct {
}

func (m *CalorimeterHit) Reset()                    { *m = CalorimeterHit{} }
func (m *CalorimeterHit) String() string            { return proto.CompactTextString(m) }
func (*CalorimeterHit) ProtoMessage()               {}
func (*CalorimeterHit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

type CalorimeterHitCollection struct {
	Hit []*CalorimeterHit `protobuf:"bytes,1,rep,name=hit" json:"hit,omitempty"`
}

func (m *CalorimeterHitCollection) Reset()                    { *m = CalorimeterHitCollection{} }
func (m *CalorimeterHitCollection) String() string            { return proto.CompactTextString(m) }
func (*CalorimeterHitCollection) ProtoMessage()               {}
func (*CalorimeterHitCollection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *CalorimeterHitCollection) GetHit() []*CalorimeterHit {
	if m != nil {
		return m.Hit
	}
	return nil
}

type Cluster struct {
}

func (m *Cluster) Reset()                    { *m = Cluster{} }
func (m *Cluster) String() string            { return proto.CompactTextString(m) }
func (*Cluster) ProtoMessage()               {}
func (*Cluster) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

type ClusterCollection struct {
	Cluster []*Cluster `protobuf:"bytes,1,rep,name=cluster" json:"cluster,omitempty"`
}

func (m *ClusterCollection) Reset()                    { *m = ClusterCollection{} }
func (m *ClusterCollection) String() string            { return proto.CompactTextString(m) }
func (*ClusterCollection) ProtoMessage()               {}
func (*ClusterCollection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *ClusterCollection) GetCluster() []*Cluster {
	if m != nil {
		return m.Cluster
	}
	return nil
}

type RecParticle struct {
}

func (m *RecParticle) Reset()                    { *m = RecParticle{} }
func (m *RecParticle) String() string            { return proto.CompactTextString(m) }
func (*RecParticle) ProtoMessage()               {}
func (*RecParticle) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

type RecParticleCollection struct {
	Particle []*RecParticle `protobuf:"bytes,1,rep,name=particle" json:"particle,omitempty"`
}

func (m *RecParticleCollection) Reset()                    { *m = RecParticleCollection{} }
func (m *RecParticleCollection) String() string            { return proto.CompactTextString(m) }
func (*RecParticleCollection) ProtoMessage()               {}
func (*RecParticleCollection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *RecParticleCollection) GetParticle() []*RecParticle {
	if m != nil {
		return m.Particle
	}
	return nil
}

func init() {
	proto.RegisterType((*EventHeader)(nil), "eicio.EventHeader")
	proto.RegisterType((*EventHeader_CollectionHeader)(nil), "eicio.EventHeader.CollectionHeader")
	proto.RegisterType((*Params)(nil), "eicio.Params")
	proto.RegisterType((*MCParticle)(nil), "eicio.MCParticle")
	proto.RegisterType((*MCParticleCollection)(nil), "eicio.MCParticleCollection")
	proto.RegisterType((*SimTrackerHit)(nil), "eicio.SimTrackerHit")
	proto.RegisterType((*SimTrackerHitCollection)(nil), "eicio.SimTrackerHitCollection")
	proto.RegisterType((*TrackerData)(nil), "eicio.TrackerData")
	proto.RegisterType((*TrackerDataCollection)(nil), "eicio.TrackerDataCollection")
	proto.RegisterType((*TrackerRawData)(nil), "eicio.TrackerRawData")
	proto.RegisterType((*TrackerRawDataCollection)(nil), "eicio.TrackerRawDataCollection")
	proto.RegisterType((*TrackerHit)(nil), "eicio.TrackerHit")
	proto.RegisterType((*TrackerHitCollection)(nil), "eicio.TrackerHitCollection")
	proto.RegisterType((*TrackerPulse)(nil), "eicio.TrackerPulse")
	proto.RegisterType((*TrackerPulseCollection)(nil), "eicio.TrackerPulseCollection")
	proto.RegisterType((*TrackerHitPlane)(nil), "eicio.TrackerHitPlane")
	proto.RegisterType((*TrackerHitPlaneCollection)(nil), "eicio.TrackerHitPlaneCollection")
	proto.RegisterType((*TrackerHitZCylinder)(nil), "eicio.TrackerHitZCylinder")
	proto.RegisterType((*TrackerHitZCylinderCollection)(nil), "eicio.TrackerHitZCylinderCollection")
	proto.RegisterType((*Track)(nil), "eicio.Track")
	proto.RegisterType((*TrackCollection)(nil), "eicio.TrackCollection")
	proto.RegisterType((*Contrib)(nil), "eicio.Contrib")
	proto.RegisterType((*SimCalorimeterHit)(nil), "eicio.SimCalorimeterHit")
	proto.RegisterType((*SimCalorimeterHitCollection)(nil), "eicio.SimCalorimeterHitCollection")
	proto.RegisterType((*RawCalorimeterHit)(nil), "eicio.RawCalorimeterHit")
	proto.RegisterType((*RawCalorimeterHitCollection)(nil), "eicio.RawCalorimeterHitCollection")
	proto.RegisterType((*CalorimeterHit)(nil), "eicio.CalorimeterHit")
	proto.RegisterType((*CalorimeterHitCollection)(nil), "eicio.CalorimeterHitCollection")
	proto.RegisterType((*Cluster)(nil), "eicio.Cluster")
	proto.RegisterType((*ClusterCollection)(nil), "eicio.ClusterCollection")
	proto.RegisterType((*RecParticle)(nil), "eicio.RecParticle")
	proto.RegisterType((*RecParticleCollection)(nil), "eicio.RecParticleCollection")
	proto.RegisterEnum("eicio.EventHeader_CollectionHeader_Type", EventHeader_CollectionHeader_Type_name, EventHeader_CollectionHeader_Type_value)
	proto.RegisterEnum("eicio.MCParticle_GenStatus", MCParticle_GenStatus_name, MCParticle_GenStatus_value)
}

func init() { proto.RegisterFile("eicio.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x57, 0xdd, 0x92, 0xdb, 0xb4,
	0x17, 0xff, 0x3b, 0xb1, 0x93, 0xf5, 0xc9, 0x47, 0x1d, 0xed, 0x47, 0xd5, 0xed, 0x1f, 0x26, 0xa3,
	0x0e, 0x10, 0xbe, 0x32, 0x74, 0x29, 0x03, 0x2d, 0x30, 0xcc, 0x4e, 0x36, 0x6d, 0x77, 0xa6, 0xbb,
	0xcd, 0x68, 0x17, 0x2e, 0xb8, 0x53, 0x1d, 0xb1, 0x2b, 0xea, 0xd8, 0xc6, 0x56, 0x5a, 0xc2, 0x1d,
	0xcf, 0xc0, 0x73, 0x70, 0xcb, 0x63, 0xf4, 0x8e, 0xc7, 0xe0, 0x1d, 0x18, 0xc9, 0x4a, 0x2c, 0x27,
	0xe9, 0x2c, 0x77, 0x3a, 0x3f, 0x9d, 0xf3, 0xd3, 0x39, 0x47, 0xe7, 0x1c, 0xd9, 0xd0, 0xe2, 0x22,
	0x14, 0xc9, 0x30, 0xcd, 0x12, 0x99, 0x20, 0x4f, 0x0b, 0xe4, 0x1f, 0x17, 0x5a, 0xe3, 0x57, 0x3c,
	0x96, 0x4f, 0x39, 0x9b, 0xf2, 0x0c, 0x75, 0xa1, 0x26, 0xa6, 0xd8, 0xe9, 0x3b, 0x03, 0x97, 0xd6,
	0xc4, 0x14, 0x1d, 0x40, 0xe3, 0xd5, 0x19, 0xfb, 0x39, 0xc9, 0x70, 0xad, 0xef, 0x0c, 0x3a, 0xd4,
	0x48, 0x05, 0x2e, 0xe2, 0x24, 0xc3, 0xf5, 0x25, 0xae, 0x24, 0x34, 0x02, 0x08, 0x93, 0x28, 0xe2,
	0xa1, 0x14, 0x49, 0x8c, 0xdd, 0x7e, 0x7d, 0xd0, 0x3a, 0xba, 0x37, 0x2c, 0x0e, 0xb6, 0xce, 0x19,
	0x8e, 0x56, 0x4a, 0x05, 0x40, 0x2d, 0x33, 0xd4, 0x87, 0xd6, 0x94, 0xe7, 0x61, 0x26, 0x52, 0xcd,
	0x12, 0xf4, 0x9d, 0x81, 0x4f, 0x6d, 0xe8, 0xf0, 0xaf, 0x3a, 0x04, 0xeb, 0x14, 0xe8, 0x1b, 0x70,
	0xe5, 0x22, 0xe5, 0xda, 0xfb, 0xee, 0xd1, 0xe0, 0x3f, 0x9c, 0x3a, 0xbc, 0x5c, 0xa4, 0x9c, 0x6a,
	0x2b, 0x84, 0xc0, 0x8d, 0xd9, 0x8c, 0xeb, 0x38, 0x7d, 0xaa, 0xd7, 0xca, 0x91, 0x94, 0x2d, 0xa2,
	0x84, 0x4d, 0x2f, 0xc4, 0x6f, 0xdc, 0x84, 0x6a, 0x43, 0xe4, 0xcf, 0x1a, 0xb8, 0x8a, 0x04, 0xed,
	0x80, 0x7b, 0xfe, 0xfc, 0x7c, 0x1c, 0xfc, 0x0f, 0x75, 0x01, 0xce, 0x46, 0x13, 0x96, 0x49, 0x11,
	0x46, 0x3c, 0x70, 0x50, 0x0f, 0x3a, 0x17, 0x62, 0x76, 0x99, 0xb1, 0xf0, 0x25, 0xcf, 0x9e, 0x0a,
	0x19, 0xd4, 0xd0, 0x2d, 0x68, 0x19, 0xf9, 0x84, 0x49, 0x16, 0xd4, 0x11, 0x82, 0xae, 0x01, 0x28,
	0x7b, 0xad, 0x31, 0x57, 0xf1, 0x58, 0x46, 0x1e, 0x0a, 0xa0, 0x6d, 0xe4, 0xc9, 0x3c, 0xca, 0x79,
	0xd0, 0x40, 0xbb, 0x70, 0xab, 0xd4, 0x98, 0x44, 0x2c, 0xe6, 0x41, 0x13, 0xdd, 0x86, 0xdd, 0x12,
	0xfc, 0x71, 0xb4, 0x88, 0x44, 0x3c, 0xe5, 0x59, 0xb0, 0x83, 0x7c, 0xf0, 0xf4, 0x46, 0xe0, 0xa3,
	0x7d, 0xe8, 0x5d, 0x88, 0xd9, 0x88, 0x45, 0x49, 0x26, 0x66, 0x5c, 0x16, 0x27, 0x80, 0x82, 0x29,
	0x7b, 0xbd, 0x06, 0xb7, 0x94, 0x73, 0x6b, 0x58, 0x1b, 0xb5, 0xa0, 0x39, 0x8a, 0xe6, 0xb9, 0xe4,
	0x59, 0xd0, 0x51, 0xe1, 0x50, 0x1e, 0xae, 0x42, 0xee, 0x22, 0x80, 0xc6, 0x0f, 0x3c, 0x93, 0xfc,
	0xd7, 0xe0, 0x16, 0x6a, 0xc3, 0x0e, 0xe5, 0x11, 0x53, 0x49, 0x0f, 0x02, 0xf2, 0xa6, 0x06, 0x8d,
	0x09, 0xcb, 0xd8, 0x2c, 0x47, 0x1f, 0x83, 0x2b, 0x62, 0x99, 0x63, 0x47, 0x17, 0xc9, 0x6d, 0x73,
	0x5d, 0xc5, 0xe6, 0xf0, 0x34, 0x96, 0xf9, 0x38, 0x96, 0xd9, 0x82, 0x6a, 0x25, 0x74, 0x1f, 0x1a,
	0x3f, 0x45, 0x09, 0x93, 0x39, 0xae, 0x69, 0xf5, 0x3b, 0x55, 0xf5, 0xc7, 0x7a, 0xaf, 0x30, 0x30,
	0x8a, 0xe8, 0x01, 0x34, 0x73, 0x99, 0x89, 0xf8, 0x2a, 0xc7, 0x75, 0x6d, 0x73, 0x58, 0xb5, 0xb9,
	0x28, 0x36, 0x0b, 0xa3, 0xa5, 0xea, 0xe1, 0x97, 0xe0, 0xaf, 0xce, 0x46, 0x01, 0xd4, 0x5f, 0xf2,
	0x85, 0x2e, 0x28, 0x9f, 0xaa, 0x25, 0xda, 0x03, 0xef, 0x15, 0x8b, 0xe6, 0x45, 0x99, 0x78, 0xb4,
	0x10, 0x1e, 0xd5, 0xbe, 0x72, 0x0e, 0x1f, 0x42, 0xcb, 0xf2, 0xe2, 0x26, 0xd3, 0x9a, 0x6d, 0xfa,
	0x08, 0xda, 0xb6, 0x33, 0x37, 0xd9, 0xfa, 0x96, 0x2d, 0xf9, 0xa3, 0x6e, 0x97, 0x1b, 0xc2, 0xd0,
	0x4c, 0x59, 0xc6, 0x97, 0x79, 0xf5, 0xe8, 0x52, 0x44, 0x87, 0xb0, 0x13, 0x5e, 0x8b, 0x68, 0x9a,
	0xf1, 0x58, 0xe7, 0xd0, 0xa3, 0x2b, 0x59, 0x1d, 0x38, 0x39, 0x79, 0xa2, 0xeb, 0xdb, 0xa3, 0x6a,
	0xa9, 0xfb, 0x5b, 0xdf, 0xa0, 0xee, 0x61, 0x87, 0x1a, 0x49, 0x75, 0x89, 0x14, 0x33, 0x8e, 0x3d,
	0x1d, 0x83, 0x5e, 0xa3, 0x36, 0x38, 0x29, 0x6e, 0x68, 0x35, 0x27, 0x55, 0x1a, 0x33, 0x96, 0xe7,
	0xb8, 0xd9, 0x77, 0x06, 0x0e, 0xd5, 0x6b, 0xc5, 0x16, 0x5e, 0xb3, 0xec, 0x8a, 0xe3, 0x1d, 0x6d,
	0x67, 0x24, 0xf4, 0x7f, 0xf0, 0x27, 0xe3, 0x78, 0x3a, 0x49, 0x44, 0x2c, 0xb1, 0xaf, 0x19, 0x4a,
	0x40, 0x31, 0xe5, 0xa9, 0x88, 0x31, 0xf4, 0xeb, 0xea, 0x2c, 0xb5, 0x56, 0x16, 0x61, 0x12, 0x25,
	0xd9, 0xe3, 0x28, 0x79, 0x8d, 0x5b, 0x3a, 0x8c, 0x12, 0x40, 0x0f, 0xc1, 0xbf, 0xe2, 0xf1, 0x85,
	0x64, 0x72, 0x9e, 0xe3, 0xb6, 0x1e, 0x03, 0x77, 0xcd, 0xa5, 0x97, 0x39, 0x1a, 0x3e, 0x59, 0xaa,
	0xd0, 0x52, 0x5b, 0x11, 0xe7, 0x62, 0x66, 0x4c, 0x3b, 0xba, 0xd1, 0x4b, 0x80, 0x0c, 0xc1, 0x5f,
	0x59, 0xa9, 0xc6, 0x7c, 0x7c, 0x7a, 0x7e, 0xfc, 0xec, 0xe2, 0xf2, 0xf8, 0x52, 0x35, 0x7c, 0x0f,
	0x3a, 0x27, 0xcf, 0x47, 0xdf, 0x9f, 0x8d, 0xcf, 0x2f, 0x8f, 0x2f, 0x4f, 0x9f, 0x9f, 0x07, 0x0e,
	0x19, 0xc3, 0x5e, 0x79, 0x60, 0x39, 0x75, 0xd0, 0xa7, 0xb0, 0x93, 0x1a, 0xd4, 0xd4, 0x7d, 0x6f,
	0xc3, 0x3f, 0xba, 0x52, 0x21, 0x7f, 0x3b, 0x6b, 0xb3, 0x43, 0xdd, 0x6f, 0xc8, 0xa3, 0xe8, 0xf4,
	0xe4, 0x33, 0x5d, 0x1e, 0x1e, 0x5d, 0x8a, 0xe5, 0xce, 0x7d, 0x53, 0x9b, 0x4b, 0x51, 0xdd, 0x6e,
	0x9a, 0x14, 0x4d, 0xe0, 0x50, 0xb5, 0x54, 0x99, 0x1d, 0x9f, 0xf0, 0x14, 0xbb, 0xc5, 0x2d, 0xaa,
	0xf5, 0xd6, 0x9b, 0xed, 0x42, 0x6d, 0x16, 0xe2, 0x86, 0xce, 0x46, 0x6d, 0x16, 0x16, 0x37, 0xdd,
	0xd4, 0x0a, 0x4e, 0x8a, 0xde, 0x05, 0x48, 0x99, 0xbc, 0x7e, 0xc6, 0xe3, 0x2b, 0x79, 0x6d, 0x6e,
	0xd6, 0x42, 0x94, 0x47, 0xbf, 0xcc, 0x59, 0x24, 0xe4, 0x02, 0xfb, 0x85, 0x47, 0x46, 0x24, 0xc7,
	0x70, 0xbb, 0x12, 0x96, 0x95, 0xa1, 0xf7, 0xa1, 0x7e, 0x2d, 0xa4, 0x49, 0xce, 0x9e, 0x49, 0x4e,
	0x45, 0x99, 0x2a, 0x05, 0xd2, 0xa9, 0x8c, 0x50, 0xf2, 0x1d, 0xec, 0x5b, 0x62, 0x85, 0xcf, 0x9d,
	0x32, 0xc9, 0x0c, 0x21, 0x32, 0x84, 0x96, 0x2e, 0xd5, 0xfb, 0x24, 0x58, 0x9f, 0xc0, 0x64, 0x0c,
	0xb8, 0x8a, 0x58, 0xac, 0x1f, 0x56, 0x58, 0xf7, 0xab, 0xac, 0x46, 0xdd, 0x10, 0xb7, 0xed, 0x31,
	0x4e, 0xbe, 0x86, 0xbd, 0xad, 0x61, 0xdf, 0xb3, 0xc3, 0xee, 0x55, 0xf9, 0x56, 0x31, 0x77, 0xab,
	0x2f, 0x00, 0x19, 0xc1, 0x81, 0x2d, 0x57, 0xfc, 0xf3, 0x52, 0x05, 0x19, 0xc2, 0xdd, 0x2a, 0xa1,
	0xd6, 0xa6, 0x85, 0x06, 0xe9, 0x6d, 0x3c, 0x22, 0xe4, 0x14, 0xee, 0xac, 0x41, 0x16, 0xf5, 0x27,
	0xe0, 0xa5, 0x0a, 0x32, 0xd4, 0x07, 0x1b, 0xbe, 0x6a, 0x03, 0x5a, 0x28, 0x91, 0xfd, 0xad, 0xaf,
	0x11, 0x39, 0x83, 0x77, 0xb6, 0xc0, 0x95, 0x53, 0xea, 0xe1, 0x22, 0x32, 0x67, 0x1c, 0x6e, 0x9c,
	0xb1, 0x32, 0xa1, 0x4a, 0x8d, 0x34, 0xcd, 0xd3, 0x46, 0xbe, 0x30, 0xc1, 0x58, 0x4c, 0x04, 0x3c,
	0xa9, 0x20, 0xc3, 0xd5, 0xb6, 0xb9, 0x68, 0xb1, 0x45, 0x7e, 0x77, 0xa0, 0x39, 0x4a, 0x62, 0x99,
	0x89, 0x17, 0xaa, 0xaa, 0xcb, 0x5e, 0x34, 0x4d, 0x66, 0x4f, 0xd8, 0x03, 0x68, 0xf0, 0x98, 0x67,
	0x57, 0x0b, 0x33, 0xc7, 0x8d, 0xb4, 0xea, 0x9f, 0xba, 0xd5, 0x3f, 0x66, 0xae, 0xba, 0xe5, 0x5c,
	0xc5, 0xea, 0x51, 0xe2, 0xe9, 0x24, 0xc9, 0xb1, 0xa7, 0xc7, 0xda, 0x52, 0x24, 0x6f, 0x9c, 0x2d,
	0x8f, 0x32, 0x7a, 0x0f, 0x1a, 0xa9, 0x7e, 0xae, 0xb4, 0x27, 0xad, 0xa3, 0x4e, 0xe5, 0x0d, 0xa3,
	0x66, 0xd3, 0x1e, 0x0b, 0xb5, 0xb7, 0x8e, 0x85, 0x7a, 0x75, 0x2c, 0x94, 0x81, 0xb8, 0x95, 0x40,
	0xcc, 0xb8, 0x28, 0xdc, 0xd3, 0xe3, 0xe2, 0x01, 0x74, 0xc2, 0x22, 0x3b, 0x73, 0x95, 0xd2, 0x5c,
	0x4f, 0x84, 0xd6, 0x51, 0xd7, 0xf8, 0x62, 0x32, 0x47, 0xab, 0x4a, 0xe4, 0x14, 0xee, 0x6e, 0xc4,
	0x63, 0xdd, 0xcb, 0x47, 0x76, 0xc5, 0xe3, 0xb2, 0xd1, 0xab, 0x06, 0x45, 0xe1, 0xef, 0x6e, 0xf9,
	0x30, 0x51, 0xfc, 0x1b, 0xe0, 0x4d, 0xfc, 0x1b, 0x06, 0x05, 0x7f, 0xb0, 0xfe, 0x85, 0x43, 0x46,
	0x80, 0xdf, 0xca, 0xfc, 0x81, 0xcd, 0xbc, 0xec, 0xfd, 0x6d, 0xb4, 0xfe, 0xea, 0x23, 0x89, 0x7c,
	0x0b, 0x3d, 0xb3, 0xb4, 0x88, 0x06, 0xd0, 0x0c, 0x0b, 0xd0, 0x90, 0xad, 0x32, 0x5a, 0xa0, 0x74,
	0xb9, 0xad, 0xa6, 0x9d, 0xf5, 0x85, 0x45, 0x9e, 0xc0, 0xbe, 0x25, 0x5a, 0x8c, 0xc3, 0x8d, 0xf7,
	0x65, 0x39, 0xf1, 0x2c, 0xfd, 0xf2, 0x81, 0x79, 0xd1, 0xd0, 0x3f, 0x03, 0x9f, 0xff, 0x1b, 0x00,
	0x00, 0xff, 0xff, 0x18, 0x77, 0xdc, 0x2d, 0x1b, 0x0c, 0x00, 0x00,
}
