# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proio.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proio.proto',
  package='proio.model',
  syntax='proto3',
  serialized_pb=_b('\n\x0bproio.proto\x12\x0bproio.model\"\xd1\x02\n\x0b\x45ventHeader\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x11\n\trunNumber\x18\x02 \x01(\x04\x12\x13\n\x0b\x65ventNumber\x18\x03 \x01(\x04\x12\x11\n\ttimeStamp\x18\x04 \x01(\x04\x12\x10\n\x08\x64\x65tector\x18\x05 \x01(\t\x12#\n\x06params\x18\x06 \x01(\x0b\x32\x13.proio.model.Params\x12\x45\n\x12payloadCollections\x18\x07 \x03(\x0b\x32).proio.model.EventHeader.CollectionHeader\x12\x12\n\nnUniqueIDs\x18\x08 \x01(\r\x12\x13\n\x0b\x64\x65scription\x18\x10 \x01(\t\x1aO\n\x10\x43ollectionHeader\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\r\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x13\n\x0bpayloadSize\x18\x04 \x01(\r\"\x1a\n\tIntParams\x12\r\n\x05\x61rray\x18\x01 \x03(\x05\"\x1c\n\x0b\x46loatParams\x12\r\n\x05\x61rray\x18\x01 \x03(\x02\"\x1d\n\x0cStringParams\x12\r\n\x05\x61rray\x18\x01 \x03(\t\"\xf2\x02\n\x06Params\x12+\n\x04ints\x18\x01 \x03(\x0b\x32\x1d.proio.model.Params.IntsEntry\x12/\n\x06\x66loats\x18\x02 \x03(\x0b\x32\x1f.proio.model.Params.FloatsEntry\x12\x31\n\x07strings\x18\x03 \x03(\x0b\x32 .proio.model.Params.StringsEntry\x1a\x43\n\tIntsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.proio.model.IntParams:\x02\x38\x01\x1aG\n\x0b\x46loatsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.proio.model.FloatParams:\x02\x38\x01\x1aI\n\x0cStringsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.proio.model.StringParams:\x02\x38\x01\",\n\tReference\x12\x0e\n\x06\x63ollID\x18\x01 \x01(\r\x12\x0f\n\x07\x65ntryID\x18\x02 \x01(\rB@\n\x05proioB\x08ProtobufZ-github.com/decibelcooper/proio/go-proio/modelb\x06proto3')
)




_EVENTHEADER_COLLECTIONHEADER = _descriptor.Descriptor(
  name='CollectionHeader',
  full_name='proio.model.EventHeader.CollectionHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='proio.model.EventHeader.CollectionHeader.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='proio.model.EventHeader.CollectionHeader.id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='proio.model.EventHeader.CollectionHeader.type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payloadSize', full_name='proio.model.EventHeader.CollectionHeader.payloadSize', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=366,
)

_EVENTHEADER = _descriptor.Descriptor(
  name='EventHeader',
  full_name='proio.model.EventHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='proio.model.EventHeader.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='runNumber', full_name='proio.model.EventHeader.runNumber', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eventNumber', full_name='proio.model.EventHeader.eventNumber', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='proio.model.EventHeader.timeStamp', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='detector', full_name='proio.model.EventHeader.detector', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='params', full_name='proio.model.EventHeader.params', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payloadCollections', full_name='proio.model.EventHeader.payloadCollections', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nUniqueIDs', full_name='proio.model.EventHeader.nUniqueIDs', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='proio.model.EventHeader.description', index=8,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_EVENTHEADER_COLLECTIONHEADER, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=366,
)


_INTPARAMS = _descriptor.Descriptor(
  name='IntParams',
  full_name='proio.model.IntParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='array', full_name='proio.model.IntParams.array', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=368,
  serialized_end=394,
)


_FLOATPARAMS = _descriptor.Descriptor(
  name='FloatParams',
  full_name='proio.model.FloatParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='array', full_name='proio.model.FloatParams.array', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=396,
  serialized_end=424,
)


_STRINGPARAMS = _descriptor.Descriptor(
  name='StringParams',
  full_name='proio.model.StringParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='array', full_name='proio.model.StringParams.array', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=426,
  serialized_end=455,
)


_PARAMS_INTSENTRY = _descriptor.Descriptor(
  name='IntsEntry',
  full_name='proio.model.Params.IntsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='proio.model.Params.IntsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='proio.model.Params.IntsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=613,
  serialized_end=680,
)

_PARAMS_FLOATSENTRY = _descriptor.Descriptor(
  name='FloatsEntry',
  full_name='proio.model.Params.FloatsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='proio.model.Params.FloatsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='proio.model.Params.FloatsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=682,
  serialized_end=753,
)

_PARAMS_STRINGSENTRY = _descriptor.Descriptor(
  name='StringsEntry',
  full_name='proio.model.Params.StringsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='proio.model.Params.StringsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='proio.model.Params.StringsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=755,
  serialized_end=828,
)

_PARAMS = _descriptor.Descriptor(
  name='Params',
  full_name='proio.model.Params',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ints', full_name='proio.model.Params.ints', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='floats', full_name='proio.model.Params.floats', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='strings', full_name='proio.model.Params.strings', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PARAMS_INTSENTRY, _PARAMS_FLOATSENTRY, _PARAMS_STRINGSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=458,
  serialized_end=828,
)


_REFERENCE = _descriptor.Descriptor(
  name='Reference',
  full_name='proio.model.Reference',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='collID', full_name='proio.model.Reference.collID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='entryID', full_name='proio.model.Reference.entryID', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=830,
  serialized_end=874,
)

_EVENTHEADER_COLLECTIONHEADER.containing_type = _EVENTHEADER
_EVENTHEADER.fields_by_name['params'].message_type = _PARAMS
_EVENTHEADER.fields_by_name['payloadCollections'].message_type = _EVENTHEADER_COLLECTIONHEADER
_PARAMS_INTSENTRY.fields_by_name['value'].message_type = _INTPARAMS
_PARAMS_INTSENTRY.containing_type = _PARAMS
_PARAMS_FLOATSENTRY.fields_by_name['value'].message_type = _FLOATPARAMS
_PARAMS_FLOATSENTRY.containing_type = _PARAMS
_PARAMS_STRINGSENTRY.fields_by_name['value'].message_type = _STRINGPARAMS
_PARAMS_STRINGSENTRY.containing_type = _PARAMS
_PARAMS.fields_by_name['ints'].message_type = _PARAMS_INTSENTRY
_PARAMS.fields_by_name['floats'].message_type = _PARAMS_FLOATSENTRY
_PARAMS.fields_by_name['strings'].message_type = _PARAMS_STRINGSENTRY
DESCRIPTOR.message_types_by_name['EventHeader'] = _EVENTHEADER
DESCRIPTOR.message_types_by_name['IntParams'] = _INTPARAMS
DESCRIPTOR.message_types_by_name['FloatParams'] = _FLOATPARAMS
DESCRIPTOR.message_types_by_name['StringParams'] = _STRINGPARAMS
DESCRIPTOR.message_types_by_name['Params'] = _PARAMS
DESCRIPTOR.message_types_by_name['Reference'] = _REFERENCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EventHeader = _reflection.GeneratedProtocolMessageType('EventHeader', (_message.Message,), dict(

  CollectionHeader = _reflection.GeneratedProtocolMessageType('CollectionHeader', (_message.Message,), dict(
    DESCRIPTOR = _EVENTHEADER_COLLECTIONHEADER,
    __module__ = 'proio_pb2'
    # @@protoc_insertion_point(class_scope:proio.model.EventHeader.CollectionHeader)
    ))
  ,
  DESCRIPTOR = _EVENTHEADER,
  __module__ = 'proio_pb2'
  # @@protoc_insertion_point(class_scope:proio.model.EventHeader)
  ))
_sym_db.RegisterMessage(EventHeader)
_sym_db.RegisterMessage(EventHeader.CollectionHeader)

IntParams = _reflection.GeneratedProtocolMessageType('IntParams', (_message.Message,), dict(
  DESCRIPTOR = _INTPARAMS,
  __module__ = 'proio_pb2'
  # @@protoc_insertion_point(class_scope:proio.model.IntParams)
  ))
_sym_db.RegisterMessage(IntParams)

FloatParams = _reflection.GeneratedProtocolMessageType('FloatParams', (_message.Message,), dict(
  DESCRIPTOR = _FLOATPARAMS,
  __module__ = 'proio_pb2'
  # @@protoc_insertion_point(class_scope:proio.model.FloatParams)
  ))
_sym_db.RegisterMessage(FloatParams)

StringParams = _reflection.GeneratedProtocolMessageType('StringParams', (_message.Message,), dict(
  DESCRIPTOR = _STRINGPARAMS,
  __module__ = 'proio_pb2'
  # @@protoc_insertion_point(class_scope:proio.model.StringParams)
  ))
_sym_db.RegisterMessage(StringParams)

Params = _reflection.GeneratedProtocolMessageType('Params', (_message.Message,), dict(

  IntsEntry = _reflection.GeneratedProtocolMessageType('IntsEntry', (_message.Message,), dict(
    DESCRIPTOR = _PARAMS_INTSENTRY,
    __module__ = 'proio_pb2'
    # @@protoc_insertion_point(class_scope:proio.model.Params.IntsEntry)
    ))
  ,

  FloatsEntry = _reflection.GeneratedProtocolMessageType('FloatsEntry', (_message.Message,), dict(
    DESCRIPTOR = _PARAMS_FLOATSENTRY,
    __module__ = 'proio_pb2'
    # @@protoc_insertion_point(class_scope:proio.model.Params.FloatsEntry)
    ))
  ,

  StringsEntry = _reflection.GeneratedProtocolMessageType('StringsEntry', (_message.Message,), dict(
    DESCRIPTOR = _PARAMS_STRINGSENTRY,
    __module__ = 'proio_pb2'
    # @@protoc_insertion_point(class_scope:proio.model.Params.StringsEntry)
    ))
  ,
  DESCRIPTOR = _PARAMS,
  __module__ = 'proio_pb2'
  # @@protoc_insertion_point(class_scope:proio.model.Params)
  ))
_sym_db.RegisterMessage(Params)
_sym_db.RegisterMessage(Params.IntsEntry)
_sym_db.RegisterMessage(Params.FloatsEntry)
_sym_db.RegisterMessage(Params.StringsEntry)

Reference = _reflection.GeneratedProtocolMessageType('Reference', (_message.Message,), dict(
  DESCRIPTOR = _REFERENCE,
  __module__ = 'proio_pb2'
  # @@protoc_insertion_point(class_scope:proio.model.Reference)
  ))
_sym_db.RegisterMessage(Reference)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\005proioB\010ProtobufZ-github.com/decibelcooper/proio/go-proio/model'))
_PARAMS_INTSENTRY.has_options = True
_PARAMS_INTSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_PARAMS_FLOATSENTRY.has_options = True
_PARAMS_FLOATSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_PARAMS_STRINGSENTRY.has_options = True
_PARAMS_STRINGSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
